import type { ReactTopic } from './types'

export const seedReactTopics: ReactTopic[] = [
  // Tab 1 — React (Fundamentals)
  {
    id: 'react-1-1', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.1 JSX & Components',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'JSX compiles to function calls; components are functions returning elements; fragments avoid wrapper divs.',
  },
  {
    id: 'react-1-2', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.2 Props & TypeScript interfaces',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Describe props with interfaces; children: ReactNode; ? marks optional; destructuring sets defaults. File: src/app/theme-provider.tsx',
  },
  {
    id: 'react-1-3', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.3 useState',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Functional updates (set(p => p+1)) when new state depends on old; lazy initializers for expensive init. Files: src/shared/hooks/usePagination.ts, src/app/theme-provider.tsx',
  },
  {
    id: 'react-1-4', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.4 useEffect',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Synchronize with external systems; cleanup prevents leaks; deps re-arm the effect. File: src/shared/hooks/useDebounce.ts',
  },
  {
    id: 'react-1-5', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.5 Conditional rendering & lists',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: '&&, ternaries, .map(); stable keys prevent DOM rebuild bugs; avoid index keys on filtered/paginated lists. File: src/shared/components/DataTable.tsx',
  },
  {
    id: 'react-1-6', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.6 Event handling & controlled inputs',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Typed callbacks; controlled inputs store value in React state via value+onChange; uncontrolled keeps DOM state.',
  },
  {
    id: 'react-1-7', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.7 Custom hooks',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Functions starting with use that extract stateful logic; each call gets its own state; no shared state between components. Files: src/shared/hooks/',
  },
  {
    id: 'react-1-8', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.8 Context API',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'createContext + Provider + useContext avoids prop-drilling; undefined default + guard throw fails loudly. File: src/app/theme-provider.tsx',
  },
  {
    id: 'react-1-9', category: 'Fundamentals', phase: 'Tab 1 — React (Fundamentals)',
    title: '1.9 Component composition',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'children prop lets parents be frames; composition over configuration; prefer children over boolean-flag props. File: src/app/router.tsx',
  },

  // Tab 2 — Tailwind & shadcn
  {
    id: 'react-2-1', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.1 Utility-first mental model',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Single-purpose utilities in markup; spacing scale: 1 unit = 0.25rem; no dead CSS or naming decisions.',
  },
  {
    id: 'react-2-2', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.2 Layout patterns',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'flex for 1-D rows/columns; grid for 2-D; shrink-0 pins sidebar; flex-1 fills remaining space. File: src/shared/components/layout/AppShell.tsx',
  },
  {
    id: 'react-2-3', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.3 Responsive & state variants',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Mobile-first breakpoints (md: = 768px+); hover:, focus-visible:, disabled: state variants; stack them freely.',
  },
  {
    id: 'react-2-4', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.4 Dark mode',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'dark: utilities activate when <html> has dark class; ThemeProvider manages the toggle via useEffect. File: src/app/theme-provider.tsx',
  },
  {
    id: 'react-2-5', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.5 Tailwind v4 specifics',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Config moved to CSS @theme blocks; no tailwind.config.js; design tokens are plain CSS custom properties. File: src/index.css',
  },
  {
    id: 'react-2-6', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.6 The cn() utility',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'clsx + tailwind-merge; resolves class conflicts (last wins); caller className overrides must come last. File: src/lib/utils.ts',
  },
  {
    id: 'react-2-7', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.7 class-variance-authority (CVA)',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Base classes + variant maps + defaults; VariantProps updates TS prop types automatically. File: src/components/ui/button.tsx',
  },
  {
    id: 'react-2-8', category: 'Tailwind & shadcn', phase: 'Tab 2 — Tailwind & shadcn',
    title: '2.8 shadcn/ui philosophy',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Components copied into src/components/ui/ via npx shadcn add; owned and editable; no npm lock-in.',
  },

  // Tab 3 — React Architectures
  {
    id: 'react-3-1', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.1 Feature-Sliced Design',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Code grouped by feature; each slice exposes a public barrel (index.ts); never import from another feature\'s internals. File: src/features/vendors/',
  },
  {
    id: 'react-3-2', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.2 App bootstrap layer',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'app/ wires providers, router, global CSS; nothing business-specific; order matters — QueryClient outermost. File: src/app/providers.tsx',
  },
  {
    id: 'react-3-3', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.3 Routing architecture',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'createBrowserRouter; :id params → useParams; <Outlet /> for nested tabs; index redirects for defaults. File: src/app/router.tsx',
  },
  {
    id: 'react-3-4', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.4 The API layer',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'One axios instance with request/response interceptors; features define flat api-objects; no component imports axios directly. File: src/config/api.ts',
  },
  {
    id: 'react-3-5', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.5 Server state with TanStack Query',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'useQuery reads, useMutation writes, invalidateQueries syncs; key factory for cache addressing; enabled: !!id guard. Files: src/shared/utils/queryKeys.ts, src/features/products/hooks/',
  },
  {
    id: 'react-3-6', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.6 Client state with Zustand',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'create() defines store hook; select narrowly to minimize re-renders; server data → Query, browser-only → Zustand. File: src/features/auth/store/auth.store.ts',
  },
  {
    id: 'react-3-7', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.7 Forms architecture',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Zod schema → z.infer type → useForm + zodResolver → mutation → invalidation; one pipeline, no exceptions. File: src/features/vendors/pages/AddVendorPage.tsx',
  },
  {
    id: 'react-3-8', category: 'Architectures', phase: 'Tab 3 — React Architectures',
    title: '3.8 Capstone: anatomy of one full data flow',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Trace URL match → router → component → useQuery → axios interceptor → cache → mutation → invalidation → refetch.',
  },

  // Tab 4 — Advanced React
  {
    id: 'react-4-1', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.1 Re-renders & referential equality',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: '{} !== {} every render; parent re-render is #1 cause of child re-renders; inline objects/arrays break memoization and effect deps.',
  },
  {
    id: 'react-4-2', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.2 useMemo / useCallback',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Cache values/functions to preserve referential equality; only useful when a memoized consumer or effect dep relies on the stable ref. File: src/shared/hooks/usePagination.ts',
  },
  {
    id: 'react-4-3', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.3 useRef & forwardRef',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Ref box survives renders without causing them; changing .current doesn\'t re-render; null until after first render.',
  },
  {
    id: 'react-4-4', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.4 React 19 features',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'use(), Actions, useActionState, useOptimistic, React Compiler direction; adopt selectively — don\'t mix Actions and RHF on same form.',
  },
  {
    id: 'react-4-5', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.5 Error boundaries & Suspense',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Error boundaries catch render errors; Suspense + React.lazy splits routes into chunks; add errorElement before lazy-loading.',
  },
  {
    id: 'react-4-6', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.6 TanStack Query advanced',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Optimistic updates with rollback (onMutate/onError), placeholderData for pagination, prefetching on hover, select to transform cache data.',
  },
  {
    id: 'react-4-7', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.7 Performance profiling',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'React DevTools Profiler records render causes; measure → identify → fix → re-measure; profile production-ish builds for timings.',
  },
  {
    id: 'react-4-8', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.8 Testing — the missing skill',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Vitest + React Testing Library + jsdom; test behavior through UI not internals; fresh QueryClient per test; query by role/label.',
  },
  {
    id: 'react-4-9', category: 'Advanced React', phase: 'Tab 4 — Advanced React',
    title: '4.9 Patterns to recognize',
    status: 'not-started',
    resource_link: '',
    project_applied: '',
    notes: 'Compound components share implicit context; render props superseded by hooks; controlled (open+onOpenChange) vs uncontrolled (defaultOpen). File: src/components/ui/dialog.tsx',
  },
]
