import type { TrackArea, TrackerId } from './types'

type RawArea = { id: string; label: string; emoji: string; phases: [string, string[]][] }

// Interview Tracker curriculum:
// DSA (5 phases, 36 items) · LLD (6 phases, 31) · HLD (6 phases, 53) ·
// Product Architecture (13 phases, 124) — ~244 items total.
const interviewRaw: RawArea[] = [
  {
    id: 'dsa',
    label: 'DSA',
    emoji: '🧮',
    phases: [
      ['Phase 1 — Foundations', [
        'Arrays & strings essentials',
        'Hashing & frequency maps',
        'Two pointers',
        'Sliding window',
        'Prefix sums & difference arrays',
        'Binary search & variants',
        'Sorting patterns & comparators',
      ]],
      ['Phase 2 — Linear Structures', [
        'Linked lists (reverse, merge, cycle)',
        'Stacks & expression evaluation',
        'Queues & deques',
        'Monotonic stack / queue',
        'Heaps & priority queues',
        'Intervals (merge, insert, overlap)',
        'Matrix traversal & in-place tricks',
      ]],
      ['Phase 3 — Trees & Graphs', [
        'Binary tree traversals',
        'Binary search trees',
        'Recursion patterns on trees (LCA, diameter)',
        'Tries & prefix search',
        'Graph representations',
        'BFS & shortest path on grids',
        'DFS & connected components',
        'Topological sort',
      ]],
      ['Phase 4 — Advanced Graphs & DP', [
        'Union-Find (DSU)',
        'Dijkstra & weighted shortest paths',
        'Minimum spanning trees',
        'Backtracking (subsets, permutations, N-Queens)',
        '1-D dynamic programming',
        '2-D / grid dynamic programming',
        'Knapsack family',
        'DP on strings (LCS, edit distance)',
      ]],
      ['Phase 5 — Advanced Topics & Mocks', [
        'Greedy & exchange arguments',
        'Bit manipulation',
        'Segment trees & Fenwick trees',
        'String algorithms (KMP, rolling hash)',
        'Math, geometry & sampling',
        'Timed mock problem sets',
      ]],
    ],
  },
  {
    id: 'lld',
    label: 'Low Level Design',
    emoji: '🧩',
    phases: [
      ['Phase 1 — OOP Foundations', [
        'Encapsulation & abstraction',
        'Inheritance vs composition',
        'Interfaces & polymorphism',
        'SOLID principles',
        'UML & class diagrams',
      ]],
      ['Phase 2 — Creational Patterns', [
        'Singleton (and why to avoid it)',
        'Factory & Abstract Factory',
        'Builder',
        'Prototype',
      ]],
      ['Phase 3 — Structural Patterns', [
        'Adapter',
        'Decorator',
        'Facade',
        'Proxy',
        'Composite & Flyweight',
      ]],
      ['Phase 4 — Behavioral Patterns', [
        'Strategy',
        'Observer',
        'Command',
        'State',
        'Template Method',
        'Chain of Responsibility',
      ]],
      ['Phase 5 — Machine Coding Drills', [
        'Parking lot',
        'Elevator system',
        'Splitwise / expense sharing',
        'Snake & Ladder / board game',
        'Rate limiter',
        'LRU / LFU cache',
      ]],
      ['Phase 6 — Concurrency & API Design', [
        'Thread-safe class design',
        'Producer–consumer & worker pools',
        'Immutability & locking strategies',
        'REST API resource design',
        'Idempotency & error contracts',
      ]],
    ],
  },
  {
    id: 'hld',
    label: 'High Level Design',
    emoji: '🏗️',
    phases: [
      ['Phase 1 — Fundamentals', [
        'Client–server model & HTTP',
        'DNS & CDNs',
        'Load balancing (L4 vs L7)',
        'Caching layers & invalidation',
        'Vertical vs horizontal scaling',
        'Latency vs throughput budgets',
        'Availability & SLAs',
        'CAP & PACELC',
      ]],
      ['Phase 2 — Storage & Databases', [
        'SQL vs NoSQL trade-offs',
        'Indexing (B-tree, LSM)',
        'Replication (leader/follower, multi-leader)',
        'Sharding & partitioning strategies',
        'Consistency models',
        'Transactions & isolation levels',
        'Key-value stores (Redis, DynamoDB)',
        'Wide-column stores (Cassandra)',
        'Search & time-series stores',
      ]],
      ['Phase 3 — Communication & Messaging', [
        'REST vs gRPC vs GraphQL',
        'WebSockets & server-sent events',
        'Message queues (SQS, RabbitMQ)',
        'Pub/Sub fan-out',
        'Kafka fundamentals (partitions, offsets)',
        'Delivery semantics (at-least/exactly-once)',
        'Idempotent consumers',
        'Backpressure & flow control',
      ]],
      ['Phase 4 — Distributed Systems Core', [
        'Consistent hashing',
        'Leader election',
        'Consensus (Raft, Paxos)',
        'Distributed locks & fencing tokens',
        'Clocks, ordering & vector clocks',
        'Quorum reads/writes',
        'Failure detection & gossip',
        'Circuit breakers & bulkheads',
        'Retries, timeouts & jitter',
        'Distributed transactions & sagas',
      ]],
      ['Phase 5 — Observability, Security & Ops', [
        'Metrics & alerting',
        'Structured logging & tracing',
        'Rate limiting & throttling',
        'AuthN / AuthZ at scale',
        'API gateways',
        'Service mesh basics',
        'Deployment strategies (blue-green, canary)',
        'Back-of-envelope capacity estimation',
      ]],
      ['Phase 6 — Case Studies', [
        'URL shortener',
        'News feed / timeline',
        'Chat system (WhatsApp)',
        'Video streaming (YouTube)',
        'Ride hailing (Uber)',
        'Search autocomplete',
        'Notification system',
        'Payment system',
        'E-commerce checkout',
        'Distributed file storage (Dropbox)',
      ]],
    ],
  },
  {
    id: 'pa',
    label: 'Product Architecture',
    emoji: '🚀',
    phases: [
      ['Phase 1 — Discovery & Requirements', [
        'Problem framing & user personas',
        'Functional requirements capture',
        'Non-functional requirements (NFRs)',
        'Success metrics & KPIs',
        'MVP scoping & slicing',
        'Roadmap & milestone planning',
        'Stakeholder alignment',
        'Trade-off analysis & decision framing',
        'Estimation & risk register',
      ]],
      ['Phase 2 — Domain Modelling', [
        'Domain-driven design basics',
        'Bounded contexts',
        'Aggregates & entities',
        'Value objects',
        'Domain events',
        'Context mapping',
        'Ubiquitous language',
        'Anti-corruption layers',
        'Event storming workshops',
      ]],
      ['Phase 3 — Architecture Styles', [
        'Monolith vs microservices',
        'Modular monolith',
        'Service decomposition strategies',
        'Hexagonal (ports & adapters)',
        'Clean architecture layering',
        'Event-driven architecture',
        'CQRS',
        'Event sourcing',
        'Serverless architectures',
        'Micro-frontends',
      ]],
      ['Phase 4 — API & Contract Design', [
        'API-first workflow',
        'REST maturity & resource modelling',
        'GraphQL schemas & federation',
        'gRPC contracts & protobuf',
        'Versioning strategies',
        'Pagination, filtering & sorting',
        'Error handling standards',
        'OpenAPI documentation',
        'Backward compatibility & deprecation',
      ]],
      ['Phase 5 — Data Architecture', [
        'Polyglot persistence',
        'Schema design & migrations',
        'Data ownership per service',
        'Change data capture (CDC)',
        'Data lakes vs warehouses',
        'ETL / ELT pipelines',
        'Analytics event design',
        'Reporting architecture',
        'Data governance & quality',
        'GDPR, PII & retention',
      ]],
      ['Phase 6 — Frontend Architecture', [
        'SPA vs SSR vs SSG',
        'State management patterns',
        'Design systems & component libraries',
        'Performance budgets',
        'Code splitting & lazy loading',
        'Backend-for-frontend (BFF)',
        'Accessibility (a11y)',
        'Internationalisation (i18n)',
        'Web vitals monitoring',
      ]],
      ['Phase 7 — Identity & Access', [
        'OAuth 2.0 flows',
        'OpenID Connect',
        'JWTs vs sessions',
        'Single sign-on (SSO)',
        'Role-based access control (RBAC)',
        'Attribute-based access control (ABAC)',
        'Multi-tenancy models',
        'Service-to-service auth & API keys',
        'Secrets management',
      ]],
      ['Phase 8 — Payments & Commerce Flows', [
        'Payment gateway integration',
        'Idempotent payment processing',
        'Double-entry ledger design',
        'Refunds & chargebacks',
        'Cart & checkout design',
        'Inventory reservation',
        'Order lifecycle & state machines',
        'Pricing, promotions & coupons',
        'Tax & invoicing',
        'Settlement & reconciliation',
      ]],
      ['Phase 9 — Scalability & Reliability', [
        'Horizontal scaling patterns',
        'Caching strategy end-to-end',
        'Queue-based load leveling',
        'Graceful degradation & fallbacks',
        'Bulkheads & isolation',
        'Chaos engineering',
        'Disaster recovery',
        'Multi-region architecture',
        'RTO / RPO planning',
        'Zero-downtime deployments',
      ]],
      ['Phase 10 — Platform & Infrastructure', [
        'Containerisation (Docker)',
        'Kubernetes fundamentals',
        'Service discovery',
        'Infrastructure as code (Terraform)',
        'CI/CD pipelines',
        'GitOps',
        'Environment strategy (dev/stage/prod)',
        'Cloud cost optimisation',
        'Autoscaling policies',
        'Edge computing & CDNs',
      ]],
      ['Phase 11 — Security & Compliance', [
        'Threat modelling (STRIDE)',
        'OWASP Top 10',
        'Encryption at rest & in transit',
        'PCI-DSS essentials',
        'Security review process',
        'Dependency & container scanning',
        'Pen-test readiness',
        'Audit logging',
        'Incident response playbooks',
      ]],
      ['Phase 12 — Observability & Operations', [
        'SLI / SLO / SLA design',
        'Golden signals',
        'Distributed tracing',
        'Log aggregation',
        'Alert design & fatigue control',
        'On-call & runbooks',
        'Blameless postmortems',
        'Feature flags',
        'A/B experimentation',
        'Release health monitoring',
      ]],
      ['Phase 13 — Leadership & Execution', [
        'Architecture decision records (ADRs)',
        'RFC / design review process',
        'Tech-debt management',
        'Build vs buy analysis',
        'Vendor evaluation',
        'Team topologies & Conway’s law',
        'Mentoring & design reviews',
        'Migration strategies (strangler fig)',
        'Legacy modernisation',
        'Communicating architecture to stakeholders',
      ]],
    ],
  },
]

// Learning Tracker curriculum — mirrors the "Tech Learning Tracker" Cowork artifact:
// P1 · Books · LLD · System Design · Product Architecture · Distributed Computing.
// Sub-groups (modules, theory/practical, sets) are rendered as their own phase sections.
const learningRaw: RawArea[] = [
  {
    id: 'p1',
    label: 'P1 · Priority 1',
    emoji: '🔥',
    phases: [
      ['Phase 0 · Module 1 — Intro to Distributed Systems for Dummies', [
        'Introduction',
        'What Distributed Systems Achieve for Us',
        'Data in Distributed Systems',
        'Communication Between Nodes',
        'Data Processing in Large Scale',
        'Distributed System Architectural Patterns',
        'Case Study 1: Apache Spark',
        'Case Study 2: Apache Druid',
      ]],
      ['Phase 0 · Module 2 — Distributed Systems for Practitioners', [
        'Introduction to Distributed Systems',
        'Basic Concepts and Theorems',
        'Distributed Transactions',
        'Achieving Isolation',
        'Achieving Atomicity',
        'Concluding Distributed Transactions',
        'Consensus',
        'Time',
        'Order',
        'Networking',
        'Security',
        'Security Protocols',
        'From Theory to Practice',
        'Case Study 1: Distributed File Systems',
        'Case Study 2: Distributed Coordination Service',
        'Case Study 3: Distributed Data Stores',
        'Case Study 4: Distributed Messaging System',
        'Case Study 5: Distributed Cluster Management',
        'Case Study 6: Distributed Ledger',
        'Case Study 7: Distributed Data Processing Systems',
        'Practices & Patterns',
        'Communication Patterns',
        'Coordination Patterns',
        'Data Synchronisation',
        'Shared-nothing Architectures',
        'Distributed Locking',
        'Compatibility Patterns',
        'Dealing with Failure',
        'Distributed Tracing',
      ]],
      ['Phase 0 · Module 3 — Building Software for the Real World', [
        'Living in Production',
        'The Exception That Grounded an Airline',
        'Stabilize Your System',
        'Stability Antipatterns',
        'Failures And Blockages',
        'Force Multiplier',
        'Stability Patterns',
        'Launching An Online Store',
        'Foundations',
        'Processes on Machines',
        'Interconnect',
        'Control Plane',
        'Security',
        'Design for Deployment',
        'Handling Versions',
        'Case Study: Trampled by Your Own Customers',
        'Adaptation',
        'System Architecture',
        'Information Architecture',
        'Chaos Engineering',
      ]],
      ['Phase 1 — Modern System Design: Theory', [
        'Introduction',
        'System Design Interviews',
        'Preliminary System Design Concepts',
        'Non-Functional System Characteristics',
        'Back-of-the-Envelope Calculations',
        'Building Blocks',
        'Domain Name System',
        'Load Balancers',
        'Databases',
        'Key-Value Store',
        'Content Delivery Network (CDN)',
        'Sequencer',
        'Distributed Monitoring',
        'Monitor Server-Side Errors',
        'Monitor Client-Side Errors',
        'Distributed Cache',
        'Distributed Messaging Queue',
        'Pub-Sub',
        'Rate Limiter',
        'Blob Store',
        'Distributed Search',
        'Distributed Logging',
        'Distributed Task Scheduler',
        'Sharded Counters',
        'Concluding the Building Blocks Discussion',
      ]],
      ['Phase 1 — Modern System Design: Use Cases', [
        'Design YouTube',
        'Design Quora',
        'Design Google Maps',
        'Design a Proximity Service / Yelp',
        'Design Uber',
        'Design Twitter',
        'Design Newsfeed System',
        'Design Instagram',
        'Design a URL Shortening Service / TinyURL',
        'Design a Web Crawler',
        'Design WhatsApp',
        'Design Typeahead Suggestion',
        'Design Collaborative Document Editing / Google Docs',
        'Design a Deployment System',
        'Design a Payment System',
        'Design a ChatGPT System',
        'Design a Data Infrastructure System',
        'LLM-Powered Customer Support Bot System Design',
        'AI-Powered Code Assistant System Design',
        'Lessons from System Failures',
        'Concluding Remarks',
        'Free System Design Lessons',
        'System Design Case Studies (Spotify, Amazon, Twilio, Dropbox, Ticketmaster)',
      ]],
      ['Phase 2 — API Design: Theory', [
        'Introduction to the Course',
        'Network Intricacies',
        'Different Ways of Client-Server Communication',
        'Common Data Formats for Web APIs',
        'Comparison of API Architectural Styles',
        'API Design Security',
        'Important Concepts in API Design',
        'Back-of-the-Envelope Calculations for Latency',
        'What Are the Foundational API Designs?',
        'API Failures and Mitigations',
        'Conclusion',
      ]],
      ['Phase 2 — API Design: Practical', [
        'Design a Search Service',
        'Design a File Service',
        'Design a Comment Service',
        'Design a Pub-Sub Service',
        'Concluding Foundational Design Problems',
        'YouTube Streaming API Design',
        'Facebook Messenger API Design',
        'Google Maps API Design',
        'Chess API Design with AI Mentor',
        'Zoom API Design',
        'Leetcode API Design',
        'Payment Gateway API Design — Stripe',
        'Twitter API Design',
        'Uber API Design',
        'CamelCamelCamel API Design',
        'Gaming API Design',
      ]],
      ['Phase 3 — Operating System: Set 1', [
        'Ch. 4 — Virtualization: Direct Execution',
        'Ch. 11 — Virtualization: Address Translation',
        'Ch. 17 — Virtualization: Swapping: Mechanisms',
        'Ch. 18 — Virtualization: Swapping: Policies',
        'Ch. 22 — Concurrency: Locks',
        'Ch. 23 — Concurrency: Locked Data Structures',
        'Ch. 24 — Concurrency: Conditional Variables',
        'Ch. 26 — Concurrency: Concurrency Bugs',
        'Ch. 27 — Concurrency: Event-Based Concurrency',
        'Ch. 31 — Persistence: Files and Directories',
        'Ch. 32 — Persistence: File System Implementation',
        'Ch. 34 — Persistence: FSCK and Journaling',
        'Ch. 36 — Persistence: Flash-based SSDs',
      ]],
      ['Phase 3 — Operating System: Set 2', [
        'Ch. 5 — Virtualization: CPU Scheduling',
        'Ch. 6 — Virtualization: Multi-Level Feedback',
        'Ch. 8 — Virtualization: Multi-CPU Scheduling',
        'Ch. 28 — Persistence: I/O Devices',
        'Ch. 29 — Persistence: Hard Disk Drives',
      ]],
      ['Phase 4 — Networking', [
        'The Application Layer',
        'The Transport Layer',
        'An Introduction to Socket Programming with Python',
        'Network Layer',
      ]],
      ['Phase 5 — Books', [
        'Distributed Systems — 1st Edition',
        'Distributed Systems — 2nd Edition',
        'AI Engineering',
        'Designing Data-Intensive Application — 1st Edition',
        'Designing Data-Intensive Application — 2nd Edition',
        'Learn Domain Driven Design',
        'Building Microservices',
        'Building Event Driven Microservices',
        'Streaming Systems',
        'Observability Engineering',
      ]],
    ],
  },
  {
    id: 'books',
    label: 'Books',
    emoji: '📚',
    phases: [
      ['Phase 0 — Finish Active Reads', [
        'PostgreSQL: Up and Running',
        'Grokking Algorithms',
      ]],
      ['Phase 1 — Go Mastery', [
        'The Go Programming Language',
        'Concurrency in Go',
        '100 Go Mistakes and How to Avoid Them',
        'Learning Go',
        'Go with the Domain',
      ]],
      ['Phase 2 — System Design Foundations', [
        'System Design Interview Vol 1',
        'System Design Interview Vol 2',
        'Clean Architecture',
        'REST API Design Rulebook',
        'API Design Patterns',
        'Fundamentals of Software Architecture',
        'Modern System Design Interviews + API Design (course)',
        'URL Shortener (practical)',
        'Pastebin (practical)',
        'TinyURL (practical)',
      ]],
      ['Phase 3 — Data Layer', [
        'Redis in Action',
        'High Performance PostgreSQL',
        'The Art of PostgreSQL',
        'MongoDB: The Definitive Guide',
        'Kafka: The Definitive Guide',
        'Kafka in Action',
        'Distributed Systems Course (data modules) (course)',
        'Kafka-backed pipeline (practical)',
        'Rate Limiter (practical)',
      ]],
      ['Phase 4 — Distributed Systems', [
        'Distributed Systems for Fun & Profit',
        'Understanding Distributed Systems',
        'Distributed Systems Observability',
        'Designing Distributed Systems',
        'RabbitMQ in Depth',
        'Distributed Systems Course (full) (course)',
        'Consistent Hashing (practical)',
        'Distributed Cache (practical)',
      ]],
      ['Phase 5 — Microservices', [
        'Microservices Patterns',
        'Hands-On Microservices with Kubernetes',
        'Modern SD Interviews (microservices) (course)',
        'Design Uber (practical)',
        'Twitter Feed (practical)',
        'Notification Service (practical)',
      ]],
      ['Phase 6 — DevOps + Cloud', [
        'Docker Deep Dive',
        'The DevOps Handbook',
        'Amazon Web Services in Action',
        'Google Cloud Platform in Action',
        'The Phoenix Project',
        'CI/CD Pipeline (practical)',
        'Cloud-native Deployment (practical)',
      ]],
      ['Phase 7 — Practice + Architecture', [
        'Software Architecture: The Hard Parts',
        'Modern Software Engineering',
        'Web Application Security',
        'Clean Code',
        'Grokking LLD (OOD) — wrap up (course)',
        'Full Mock System Design Interviews (practical)',
      ]],
    ],
  },
  {
    id: 'lld',
    label: 'LLD',
    emoji: '🏗️',
    phases: [
      ['Phase 0 — Practice Track (8 Problems)', [
        'Week 1: Design a Parking Lot',
        'Week 2: Design a Library System',
        'Week 3: Design an ATM',
        'Week 4: Design a Hotel Booking System',
        'Week 5: Design Chess / Snake & Ladder',
        'Week 6: Design an Elevator System',
        'Week 7: Design a Vending Machine',
        'Week 8: Design Amazon Locker',
      ]],
      ['Phase 1 — OOP Foundations', [
        'Background of OOP',
        'Encapsulation',
        'Abstraction',
        'Inheritance',
        'Generalization',
        'Polymorphism',
      ]],
      ['Phase 2 — OOAD', [
        'Introduction to OOAD',
        'UML Foundations',
        'Use Case Diagram',
        'Class Diagram',
        'Sequence Diagram',
        'Activity Diagram',
      ]],
      ['Phase 3 — SOLID Principles', [
        'Single Responsibility Principle',
        'Open Closed Principle',
        'Liskov Substitution Principle',
        'Interface Segregation Principle',
        'Dependency Inversion Principle',
      ]],
      ['Phase 4 — Design Patterns', [
        'Creational Patterns',
        'Structural Patterns',
        'Behavioral Patterns',
        'Architectural Patterns',
      ]],
      ['Phase 5 — OO Design Thinking', [
        'Requirement Analysis',
        'Domain Modeling',
        'Design Process',
        'Engineering Decisions',
        'Validation & Edge Cases',
      ]],
      ['Phase 6 — Interview Prep', [
        'Mock Interviews & Cheat Sheets',
      ]],
    ],
  },
  {
    id: 'sd',
    label: 'System Design',
    emoji: '⚙️',
    phases: [
      ['Phase 1 — Foundations', [
        'Introduction to Modern System Design',
        'Why System Design Matters',
        'System Design Interviews',
        'Abstractions in Distributed Systems',
        'RPC',
        'Consistency Models',
        'Failure Models',
        'Availability',
        'Reliability',
        'Scalability',
        'Maintainability',
        'Fault Tolerance',
        'Back-of-the-envelope Calculations',
      ]],
      ['Phase 2 — Core Building Blocks', [
        'DNS',
        'Load Balancers',
        'Database Types',
        'Replication',
        'Partitioning',
        'Database Trade-offs',
        'CDN',
        'Sequencer',
        'Distributed Monitoring',
        'Monitoring Systems',
        'Distributed Cache',
        'Messaging Queue',
        'Pub-Sub',
        'Rate Limiter',
        'Blob Store',
        'Distributed Search',
        'Distributed Logging',
        'Distributed Task Scheduler',
        'Sharded Counters',
      ]],
      ['Phase 3 — Architecture Thinking', [
        'RESHADED Framework',
        'Distributed Design Patterns',
        'System Analysis vs System Design',
        'API Design',
        'Large Scale Reliability',
        'System Failure Analysis',
        'Performance Optimization',
      ]],
      ['Phase 4 — Modern AI System Theory', [
        'Data Infrastructure for AI/ML',
        'ChatGPT System Concepts',
        'LLM Customer Support Architecture',
        'AI Code Assistant Architecture',
        'Modern Data Pipelines',
        'AI Reliability',
        'AI Scaling Concepts',
        'Lessons from Real Outages',
      ]],
    ],
  },
  {
    id: 'pa',
    label: 'Product Architecture',
    emoji: '🧱',
    phases: [
      ['Phase 0 — Foundation', [
        'What Product Architecture Means',
        'Product Architecture vs System Design',
        'Product Requirements → Architecture',
        'Functional vs Non-Functional Requirements',
        'API-first Thinking',
        'Business Considerations',
        'Design Principles',
        'Scalability Basics',
        'Reliability Basics',
        'Availability Basics',
        'Maintainability',
        'Extensibility',
        'Cost Awareness',
      ]],
      ['Phase 1 — Internet & Network Foundations', [
        'Internet Fundamentals',
        'Network Layers',
        'Packets',
        'Latency',
        'Bandwidth',
        'Throughput',
        'Connections',
        'TCP',
        'UDP',
        'DNS',
        'Narrow Waist of Internet',
        'HTTP Evolution',
        'HTTP',
        'Request Journey',
      ]],
      ['Phase 2 — Web Communication Models', [
        'Client Server Model',
        'HTTP Methods',
        'REST',
        'REST Constraints',
        'RESTful APIs',
        'Long Polling',
        'WebSockets',
        'Streaming',
        'gRPC',
        'GraphQL',
        'Client Adaptation',
      ]],
      ['Phase 3 — Data Representation & API Contracts', [
        'Data Representation',
        'Serialization Basics',
        'Protocol Buffers',
        'Binary Formats',
        'Deserialization',
        'Query Patterns',
        'Validation',
        'Forward Compatibility',
        'Backward Compatibility',
        'Payload Optimization',
        'Resource Hints',
      ]],
      ['Phase 4 — API Architecture Styles', [
        'API Architecture Overview',
        'API Governance',
      ]],
      ['Phase 5 — Security Foundations', [
        'Security Principles',
        'CIA Model',
        'Authentication',
        'Authorization',
        'OAuth',
        'OpenID',
        'SAML',
        'Tokens',
        'TLS',
        'Encryption',
        'CORS',
        'Certificates',
        'Sessions',
        'Input Validation',
        'Security Architecture',
      ]],
      ['Phase 6 — Advanced API Engineering', [
        'API Versioning',
        'API Evolution',
        'Rate Limiting',
        'Idempotency',
        'Monitoring (API)',
        'Observability',
        'Architecture Conventions',
        'Event Architecture',
      ]],
      ['Phase 7 — Performance Engineering', [
        'Throughput vs Latency',
        'Caching Layers',
        'Throughput Analysis',
        'Latency Estimation',
        'Processing Time',
        'Performance Budgeting',
        'Response Time',
        'Queue Delays',
        'Capacity Estimation',
        'CDN Basics',
        'Network Optimization',
      ]],
      ['Phase 8 — Foundational Design Frameworks', [
        'Architectural Evolution',
      ]],
      ['Phase 9 — Failure Engineering', [
        'Failure Taxonomy',
        'Reliability Engineering',
        'Incident Management',
        'Causes of API Failures',
        'Resilience Design',
        'Amazon S3 Outage Case Study',
        'Knight Capital Failure Case Study',
        'Uber Failures Case Study',
        'Facebook Failures Case Study',
        'Recovery Patterns',
      ]],
    ],
  },
  {
    id: 'dc',
    label: 'Distributed Computing',
    emoji: '🌐',
    phases: [
      ['Phase 0 — Mental Model Setup', [
        'Fallacies of Distributed Computing',
      ]],
      ['Phase 1 — Physical Infrastructure', [
        'Node Communication',
        'Network Layer',
      ]],
      ['Phase 2 — Clocks & Time', [
        'Time in Distributed Systems',
        'Theoretical Perspective on Time',
        'Practical Perspective on Time',
        'Logical Clocks',
        'Lamport Clocks',
        'Vector Clocks',
        'Dotted Version Vectors',
        'Event Ordering',
        'Partial Ordering',
        'Total Ordering',
        'Distributed Snapshot Problem',
      ]],
      ['Phase 3 — Replication', [
        'Replication',
        'Primary Backup Replication',
        'Multi Primary Replication',
      ]],
      ['Phase 4 — Consensus', [
        'Consensus Problem',
        'Paxos',
        'Paxos Complexity',
        'Paxos in Production',
        'Raft',
        'Raft Implementation',
        'Distributed Transactions via Consensus',
      ]],
      ['Phase 5 — Transactions', [
        'Distributed Transactions',
        'Optimistic Concurrency Control',
        'Atomicity Challenges',
        'Types of Failures',
      ]],
      ['Phase 6 — Security (DC)', [
        'Authentication',
        'OAuth',
        'TLS',
        'Symmetric Encryption',
        'Asymmetric Encryption',
        'Digital Signatures',
        'Confidentiality',
        'Integrity',
        'Cryptography Primer',
      ]],
      ['Phase 7 — Scalability', [
        'Scalability',
        'Horizontal vs Vertical Scaling',
        'Partitioning',
        'Horizontal Partitioning Algorithms',
      ]],
      ['Phase 8 — Theory Consolidation', [
        'Failure in Distributed Systems',
      ]],
    ],
  },
]

function buildAreas(raw: RawArea[]): TrackArea[] {
  return raw.map((a) => ({
    id: a.id,
    label: a.label,
    emoji: a.emoji,
    phases: a.phases.map(([title, items], pi) => ({
      id: `${a.id}-p${pi + 1}`,
      title,
      items: items.map((t, ii) => ({ id: `${a.id}-p${pi + 1}-i${ii + 1}`, title: t })),
    })),
  }))
}

export const trackerAreas: Record<TrackerId, TrackArea[]> = {
  interview: buildAreas(interviewRaw),
  learning: buildAreas(learningRaw),
}

export function countAreaItems(areas: TrackArea[]) {
  return areas.reduce((sum, a) => sum + a.phases.reduce((s, p) => s + p.items.length, 0), 0)
}
