import type { StudyWeek, UseCase } from './types'

export const seedStudyWeeks: StudyWeek[] = [
  {
    id: 'sw-1a',
    weekNum: '1',
    weekTitle: 'Week 1 — Python for AI',
    phase: 'Foundation — Weeks 1–2',
    topics: [
      { text: 'async/await and coroutines — the backbone of agent loops', done: false },
      { text: 'Type hints and dataclasses for clean, debuggable code', done: false },
      { text: 'Decorators (you\'ll use @tool constantly in LangChain)', done: false },
      { text: 'Working with JSON — every LLM response is JSON', done: false },
      { text: 'Virtual environments with venv or conda', done: false },
      { text: 'HTTP requests with httpx (async-friendly)', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-1b',
    weekNum: '1',
    weekTitle: 'Week 1 — How LLMs Work',
    phase: 'Foundation — Weeks 1–2',
    topics: [
      { text: 'What tokens are — and why they determine your cost', done: false },
      { text: 'Context windows: why 128K tokens still feels small for agents', done: false },
      { text: 'Temperature, top-p, top-k — what to set and when', done: false },
      { text: 'Base model vs instruction-tuned vs RLHF-tuned models', done: false },
      { text: 'Why hallucinations happen (and can\'t be fully fixed)', done: false },
      { text: 'Watch: Andrej Karpathy "Intro to LLMs" on YouTube (90 min)', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-2',
    weekNum: '2',
    weekTitle: 'Week 2 — Prompt Engineering',
    phase: 'Foundation — Weeks 1–2',
    topics: [
      { text: 'Zero-shot vs few-shot — when examples matter', done: false },
      { text: 'Chain-of-thought (CoT): force the model to reason before answering', done: false },
      { text: 'System prompt design: role, rules, format, tone', done: false },
      { text: 'XML tags for structured, parseable prompts', done: false },
      { text: 'JSON mode and structured output', done: false },
      { text: 'Writing tool descriptions models actually follow', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-3',
    weekNum: '3',
    weekTitle: 'Week 3 — LLM APIs (Raw)',
    phase: 'Phase 1 — AI Application Engineering',
    topics: [
      { text: 'OpenAI API: messages array, roles, parameters', done: false },
      { text: 'Anthropic Claude API — structure differences from OpenAI', done: false },
      { text: 'Gemini API basics', done: false },
      { text: 'Streaming responses (Server-Sent Events)', done: false },
      { text: 'Rate limit handling with exponential backoff', done: false },
      { text: 'Token counting and exact cost calculation per request', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-4',
    weekNum: '4',
    weekTitle: 'Week 4 — Embeddings & Vector Databases',
    phase: 'Phase 1 — AI Application Engineering',
    topics: [
      { text: 'What embeddings are — semantic meaning as floating-point vectors', done: false },
      { text: 'Cosine similarity explained intuitively', done: false },
      { text: 'Generating embeddings via OpenAI or Cohere API', done: false },
      { text: 'FAISS for local, fast, zero-setup vector search', done: false },
      { text: 'Pinecone or Chroma for managed vector storage', done: false },
      { text: 'Indexing strategies and metadata filtering', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-5',
    weekNum: '5',
    weekTitle: 'Week 5 — RAG (Retrieval Augmented Generation)',
    phase: 'Phase 1 — AI Application Engineering',
    topics: [
      { text: 'Document loaders: PDF, web pages, markdown, CSV', done: false },
      { text: 'Text splitting: chunk size, overlap, recursive splitting', done: false },
      { text: 'Why chunk size dramatically affects answer quality', done: false },
      { text: 'Retrieval: similarity search vs Maximal Marginal Relevance (MMR)', done: false },
      { text: 'Context injection: how retrieved text goes into the prompt', done: false },
      { text: 'LangChain vs LlamaIndex for RAG — when to pick which', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-6',
    weekNum: '6',
    weekTitle: 'Week 6 — LangChain Core',
    phase: 'Phase 1 — AI Application Engineering',
    topics: [
      { text: 'LCEL pipe syntax (|) — composing chains elegantly', done: false },
      { text: 'ChatPromptTemplate and MessagesPlaceholder', done: false },
      { text: 'Output parsers: StrOutputParser, JsonOutputParser, Pydantic', done: false },
      { text: '@tool decorator for defining tools', done: false },
      { text: '.bind_tools() — attaching tools to a model', done: false },
      { text: 'ConversationBufferMemory and managing chat history', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-7',
    weekNum: '7',
    weekTitle: 'Week 7 — First Real Projects',
    phase: 'Phase 1 — AI Application Engineering',
    topics: [
      { text: 'Combining RAG + LangChain in one system', done: false },
      { text: 'Multi-turn conversation with memory', done: false },
      { text: 'Handling "I don\'t know" gracefully', done: false },
      { text: 'Structured output for consistent downstream use', done: false },
      { text: 'Integrating product catalogs as knowledge bases', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-8',
    weekNum: '8',
    weekTitle: 'Week 8 — Architecture Patterns',
    phase: 'Phase 2 — AI System Design',
    topics: [
      { text: 'Naive RAG vs Advanced RAG (HyDE, reranking, hybrid search)', done: false },
      { text: 'Context window management: what to include vs summarize vs cache', done: false },
      { text: 'Multi-model routing: fast cheap model for simple, GPT-4 for complex', done: false },
      { text: 'Semantic caching with GPTCache to cut repeat API costs', done: false },
      { text: 'Cost math: calculating cost at scale (tokens × price × daily volume)', done: false },
      { text: 'Embedding model tradeoffs: speed vs accuracy vs cost', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-9',
    weekNum: '9',
    weekTitle: 'Week 9 — Evaluation Frameworks',
    phase: 'Phase 2 — AI System Design',
    topics: [
      { text: 'Building an eval dataset: question + expected answer + rubric', done: false },
      { text: 'RAGAS metrics: faithfulness, answer relevancy, context precision', done: false },
      { text: 'LangSmith: setup, tracing every LLM call, comparing experiments', done: false },
      { text: 'LLM-as-judge: using GPT-4 to grade your bot\'s outputs', done: false },
      { text: 'Tracking quality improvements across iterations', done: false },
      { text: 'Why eval is the most neglected skill — and why it matters most', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-10',
    weekNum: '10',
    weekTitle: 'Week 10 — Observability & Production Readiness',
    phase: 'Phase 2 — AI System Design',
    topics: [
      { text: 'Structured logging of every LLM call (model, tokens, latency, cost)', done: false },
      { text: 'Latency tracking: P50, P95, P99 — where is time being lost?', done: false },
      { text: 'Token usage dashboards per user / per feature', done: false },
      { text: 'Retry logic with exponential backoff and jitter', done: false },
      { text: 'Fallback models: if GPT-4 fails → Claude Haiku', done: false },
      { text: 'Cost guardrails: max-token budgets per request', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-11',
    weekNum: '11',
    weekTitle: 'Week 11 — System Design Projects',
    phase: 'Phase 2 — AI System Design',
    topics: [
      { text: 'Query classification and intent routing', done: false },
      { text: 'Multi-source RAG with metadata filtering', done: false },
      { text: 'Knowledge base architecture for large document sets', done: false },
      { text: 'Capacity planning: estimating cost and latency at 10K daily users', done: false },
      { text: 'Writing a technical design document', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-12',
    weekNum: '12',
    weekTitle: 'Week 12 — The Agent Mental Model',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'What an agent is: model + tools + memory + loop', done: false },
      { text: 'The ReAct pattern: Reason → Act → Observe → Repeat', done: false },
      { text: 'Exit conditions: how agents decide they\'re done', done: false },
      { text: 'Implementing a ReAct loop from scratch with raw API calls', done: false },
      { text: 'Common failure modes: infinite loops, hallucinated tool calls', done: false },
      { text: 'Max iterations: the only thing preventing infinite cost', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-13',
    weekNum: '13',
    weekTitle: 'Week 13 — Tool Calling Deep Dive',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'Function calling at the OpenAI/Anthropic API level (schemas)', done: false },
      { text: 'Tool description quality — the #1 factor in tool use accuracy', done: false },
      { text: 'Parallel tool calling: multiple tools in one model turn', done: false },
      { text: 'Tool error handling: what to do when a tool fails mid-run', done: false },
      { text: 'Building real tools: inventory DB, pricing engine, shipping API', done: false },
      { text: 'Dangerous tools: requiring confirmation before execution', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-14',
    weekNum: '14',
    weekTitle: 'Week 14 — LangGraph Fundamentals',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'StateGraph and TypedDict: defining what state your agent tracks', done: false },
      { text: 'Nodes: just Python functions that read and write state', done: false },
      { text: 'Fixed edges: deterministic transitions between nodes', done: false },
      { text: 'Conditional edges: routing based on what\'s in state', done: false },
      { text: 'START and END nodes', done: false },
      { text: 'MemorySaver: persisting state across turns', done: false },
      { text: 'Compiling and running a graph', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-15',
    weekNum: '15',
    weekTitle: 'Week 15 — Advanced LangGraph',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'Subgraphs: agents as nodes inside larger graphs', done: false },
      { text: 'human-in-the-loop with interrupt() — pausing mid-run', done: false },
      { text: 'interrupt_before vs interrupt_after', done: false },
      { text: 'Resuming from a checkpoint after human input', done: false },
      { text: 'Streaming with astream_events for real-time output', done: false },
      { text: 'Thread IDs: multi-user isolated sessions with checkpointing', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-16',
    weekNum: '16',
    weekTitle: 'Week 16 — Multi-Agent Systems',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'Supervisor pattern: one agent routes to specialists', done: false },
      { text: 'Swarm pattern: agents hand off dynamically to each other', done: false },
      { text: 'Shared state between agents in a graph', done: false },
      { text: 'Preventing infinite loops and runaway costs', done: false },
      { text: 'CrewAI: role-based multi-agent framework (great for prototyping)', done: false },
      { text: 'AutoGen: Microsoft\'s framework, strong for code-generation agents', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-17',
    weekNum: '17',
    weekTitle: 'Week 17 — LangGraph Platform & Deployment',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'LangGraph Studio: visual graph debugger — see your graph run live', done: false },
      { text: 'Deploying graphs as HTTP APIs', done: false },
      { text: 'Streaming responses over HTTP (Server-Sent Events)', done: false },
      { text: 'Thread management: isolating sessions for multiple users', done: false },
      { text: 'LangSmith production tracing and alerting', done: false },
      { text: 'Long-running agent runs: timeouts, retries, status polling', done: false },
    ],
    status: 'not-started',
  },
  {
    id: 'sw-18',
    weekNum: '18',
    weekTitle: 'Week 18 — Capstone Project',
    phase: 'Phase 3 — Agentic AI',
    topics: [
      { text: 'Combining all phases into a production system', done: false },
      { text: 'System design: how the components connect', done: false },
      { text: 'Eval suite: 50-question ground truth, RAGAS scores', done: false },
      { text: 'Full LangSmith observability dashboard', done: false },
      { text: 'Cost guards and safety nets', done: false },
      { text: 'Final presentation: architecture diagram + demo', done: false },
    ],
    status: 'not-started',
  },
]

export const seedUseCases: UseCase[] = [
  {
    id: 'uc-1',
    weekNum: '1',
    phase: 'Foundation — Weeks 1–2',
    title: 'Async Product Price Tracker',
    description: 'Build an async Python script that fetches 10 product records concurrently from a mock API using asyncio.gather(). Handles retries, timeouts, and saves results as JSON. Focus: getting comfortable with async patterns you\'ll use in every agent.',
    status: 'not-started',
  },
  {
    id: 'uc-2',
    weekNum: '2',
    phase: 'Foundation — Weeks 1–2',
    title: 'Product Review Sentiment Classifier',
    description: 'Using only direct API calls (no frameworks), classify 20 mock customer reviews as Positive / Neutral / Negative with a 1-5 star score. Compare zero-shot vs CoT vs few-shot — log accuracy of each approach. This teaches you prompt craft before frameworks hide it.',
    status: 'not-started',
  },
  {
    id: 'uc-3',
    weekNum: '3',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'AI Product Description Generator',
    description: 'Call OpenAI API directly (no LangChain) to generate product descriptions for 10 different categories (electronics, clothing, food, tools, cosmetics...). Implement streaming so text appears word-by-word. Track token usage and log the exact cost of each call.',
    status: 'not-started',
  },
  {
    id: 'uc-4',
    weekNum: '4',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Product Similarity Search Engine',
    description: 'Embed 100 mock product descriptions using OpenAI text-embedding-3-small. Build a search function that takes a natural language query ("waterproof running shoes under ₹3000") and returns the top 5 most similar products with similarity scores. Use FAISS locally.',
    status: 'not-started',
  },
  {
    id: 'uc-5',
    weekNum: '5',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Product Manual FAQ Chatbot',
    description: 'Build a RAG chatbot over 5 product manuals (create mock PDFs for 5 electronics). It answers customer questions with exact citations: "According to the warranty section on page 3...". It explicitly says "I don\'t know" when the answer isn\'t in the docs. Use LlamaIndex.',
    status: 'not-started',
  },
  {
    id: 'uc-6',
    weekNum: '6',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Customer Review Analyzer Chain',
    description: 'LangChain LCEL chain that: reads 5 customer reviews → extracts sentiment + star rating per review → identifies the top 3 recurring themes → generates a prioritized list of product improvements for the team. Uses Pydantic structured output throughout.',
    status: 'not-started',
  },
  {
    id: 'uc-7a',
    weekNum: '7A',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Shopping Assistant Chatbot',
    description: 'Full chatbot over a 50-product JSON catalog. Remembers conversation context ("do you have something cheaper?" knows what the previous product was). Uses LangChain + ConversationBufferMemory + structured product lookup.',
    status: 'not-started',
  },
  {
    id: 'uc-7b',
    weekNum: '7B',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Store Policy Bot (RAG)',
    description: 'RAG chatbot over 3 policy documents: return policy, shipping policy, privacy policy. Multi-turn memory. Responds with policy quotes, handles edge cases with "I\'m not sure — please contact our support team."',
    status: 'not-started',
  },
  {
    id: 'uc-7c',
    weekNum: '7C',
    phase: 'Phase 1 — AI Application Engineering',
    title: 'Personalized Product Recommender',
    description: 'Asks user 3 preference questions (budget, category, use case). Uses the answers + product catalog to recommend top 3 items with a reason for each. Structured Pydantic output. Clean LangChain chain.',
    status: 'not-started',
  },
  {
    id: 'uc-8',
    weekNum: '8',
    phase: 'Phase 2 — AI System Design',
    title: 'Smart Product Search v2 (Hybrid)',
    description: 'Upgrade your Week 4 similarity search: add BM25 keyword search alongside semantic search (hybrid retrieval). Add a Cohere Rerank API call to rerank top-20 results to top-5. Route simple single-word queries to a fast cheap model and complex queries to GPT-4. Measure and log latency and cost per query type.',
    status: 'not-started',
  },
  {
    id: 'uc-9',
    weekNum: '9',
    phase: 'Phase 2 — AI System Design',
    title: 'FAQ Bot Quality Evaluator',
    description: 'For your Week 5 FAQ Chatbot: write 30 question-answer ground truth pairs. Run RAGAS evaluation (faithfulness, answer relevancy). Set up LangSmith to trace every query. Build a script that runs the full eval suite and prints a quality scorecard. Target: faithfulness > 0.85.',
    status: 'not-started',
  },
  {
    id: 'uc-10',
    weekNum: '10',
    phase: 'Phase 2 — AI System Design',
    title: 'Production-Grade Support Bot',
    description: 'Take your Week 7B Store Policy Bot and add: full LangSmith tracing, per-query cost logging, latency measurement (log P50 and P95), automatic fallback to Claude Haiku if OpenAI errors, and a hard cost guard that refuses to answer if the prompt would cost more than ₹2.',
    status: 'not-started',
  },
  {
    id: 'uc-11a',
    weekNum: '11A',
    phase: 'Phase 2 — AI System Design',
    title: 'Customer Support Triage System',
    description: 'Classifier that reads an incoming customer message and routes it to one of 4 handlers: OrderIssueHandler, ProductQuestionHandler, ReturnRequestHandler, GeneralHandler. Each handler uses its own RAG knowledge base. Logs classification + confidence score.',
    status: 'not-started',
  },
  {
    id: 'uc-11b',
    weekNum: '11B',
    phase: 'Phase 2 — AI System Design',
    title: 'Internal Ops Knowledge Assistant',
    description: 'RAG over 10 supplier contracts + product spec sheets. Answers questions with document name + section citation. Handles ambiguous queries by saying what it found and what it\'s uncertain about. Uses LlamaIndex metadata filtering.',
    status: 'not-started',
  },
  {
    id: 'uc-11c',
    weekNum: '11C',
    phase: 'Phase 2 — AI System Design',
    title: 'Catalog Search System Design Doc',
    description: 'Write a design document: how would you build semantic search for 50,000 products? Cover chunking strategy, embedding model choice, vector DB selection, latency targets, cost-per-query estimate, and catalog refresh strategy when products update daily.',
    status: 'not-started',
  },
  {
    id: 'uc-12',
    weekNum: '12',
    phase: 'Phase 3 — Agentic AI',
    title: 'Order Status ReAct Agent (No Framework)',
    description: 'Pure ReAct loop with zero frameworks. The agent receives an order ID, reasons about what to do, calls mock tools (get_order_status, get_shipping_info, estimate_delivery) via raw function calling, observes results, and generates a customer-facing status update. Implement the loop yourself — this is where agents click.',
    status: 'not-started',
  },
  {
    id: 'uc-13',
    weekNum: '13',
    phase: 'Phase 3 — Agentic AI',
    title: 'Discount & Checkout Calculator Agent',
    description: 'Agent with 5 mock tools: check_inventory(product_id), calculate_discount(cart_total, user_tier), get_shipping_rate(city, weight_kg), apply_coupon(code, cart_total), get_product_details(id). User says: "I want 3 units of product X, I have coupon SAVE20, ship to Mumbai." Agent figures out the full order total.',
    status: 'not-started',
  },
  {
    id: 'uc-14',
    weekNum: '14',
    phase: 'Phase 3 — Agentic AI',
    title: 'Order Validation Pipeline (LangGraph)',
    description: 'LangGraph graph with 5 nodes: check_inventory → validate_address → verify_payment → calculate_final_price → approve_or_reject. Each node updates shared state. Conditional edges: if any check fails, route to a rejection node that explains exactly which step failed. If all pass, route to order confirmation.',
    status: 'not-started',
  },
  {
    id: 'uc-15',
    weekNum: '15',
    phase: 'Phase 3 — Agentic AI',
    title: 'Returns & Refund Agent (Human-in-the-Loop)',
    description: 'LangGraph agent that handles return requests end-to-end: verify purchase → check return eligibility → calculate refund → if refund > ₹5,000: interrupt() and show human a summary to approve/reject → on approval: process refund and draft confirmation email. Streams all status updates in real-time.',
    status: 'not-started',
  },
  {
    id: 'uc-16',
    weekNum: '16',
    phase: 'Phase 3 — Agentic AI',
    title: 'E-commerce Customer Support System (Multi-Agent)',
    description: 'Supervisor agent routes to 4 specialists: ProductInfoAgent (RAG over catalog), OrderTrackingAgent (mock order DB), ReturnsAgent (full return flow with human-in-the-loop), RecommendationAgent (personalized suggestions). Agents can hand off to each other. Build first in LangGraph, then replicate the routing in CrewAI — compare the two approaches.',
    status: 'not-started',
  },
  {
    id: 'uc-17',
    weekNum: '17',
    phase: 'Phase 3 — Agentic AI',
    title: 'Deploy Support System as a Live API',
    description: 'Take your Week 16 multi-agent system and deploy it: expose a /chat endpoint with streaming support, add thread_id per user for isolated sessions, wire up LangSmith for a production dashboard showing: daily query volume, average latency, error rate, cost per day.',
    status: 'not-started',
  },
  {
    id: 'uc-18',
    weekNum: '18',
    phase: 'Phase 3 — Agentic AI',
    title: 'Full E-commerce AI Assistant (Capstone)',
    description: 'Production-grade system combining everything: Product Q&A (RAG over catalog + manuals), order management (check status, update, cancel), returns & refunds (human approval for amounts > ₹5K), personalized recommendations, email drafting, human-in-the-loop for sensitive actions, full streaming UI, LangSmith observability dashboard, eval suite: 50-question ground truth with RAGAS scores, cost guard: max ₹5 per conversation session.',
    status: 'not-started',
  },
]
