import type { GoTopic } from './types'
export const seedGoTopics: GoTopic[] = [
  { id: 'go-1', category: 'Language Fundamentals', phase: 'Foundation', title: 'Interfaces and method sets', status: 'practiced', resource_link: 'https://go.dev/tour/methods/9', applied_in_project: 'cloud-engineering-labs', notes: 'Keep interfaces small and consumer-owned.' },
  { id: 'go-2', category: 'Language Fundamentals', phase: 'Foundation', title: 'Error handling with fmt.Errorf and %w', status: 'practiced', resource_link: 'https://go.dev/blog/go1.13-errors', applied_in_project: 'cloud-engineering-labs', notes: 'Wrap with context; unwrap with errors.Is/As.' },
  { id: 'go-3', category: 'Language Fundamentals', phase: 'Applied Practice', title: 'Generics and type constraints', status: 'learning', resource_link: 'https://go.dev/doc/faq#generics', applied_in_project: '', notes: 'Use generics when it removes real duplication.' },
  { id: 'go-4', category: 'Concurrency', phase: 'Foundation', title: 'Goroutines and cancellation', status: 'learning', resource_link: 'https://go.dev/blog/context', applied_in_project: 'distributed-systems-lab', notes: 'Always ensure a goroutine has a termination path.' },
  { id: 'go-5', category: 'Concurrency', phase: 'Applied Practice', title: 'Channels, select, and backpressure', status: 'mastered', resource_link: '', applied_in_project: '', notes: 'Avoid closing channels from receivers; nil channels can gate select cases.' },
  { id: 'go-6', category: 'Concurrency', phase: 'Applied Practice', title: 'Worker pool pattern', status: 'learning', resource_link: '', applied_in_project: 'distributed-systems-lab', notes: 'Bound goroutines with a semaphore or a fixed pool.' },
  { id: 'go-7', category: 'Concurrency', phase: 'Production-Ready', title: 'Context propagation across service boundaries', status: 'not-started', resource_link: '', applied_in_project: '', notes: '' },
  { id: 'go-8', category: 'Standard Library', phase: 'Foundation', title: 'net/http server design', status: 'practiced', resource_link: '', applied_in_project: 'cloud-engineering-labs', notes: '' },
  { id: 'go-9', category: 'Standard Library', phase: 'Foundation', title: 'io.Reader and io.Writer composition', status: 'mastered', resource_link: '', applied_in_project: 'cloud-engineering-labs', notes: 'Compose transformations using TeeReader and MultiWriter.' },
  { id: 'go-10', category: 'Testing & Benchmarking', phase: 'Foundation', title: 'Table-driven tests', status: 'not-started', resource_link: '', applied_in_project: '', notes: '' },
  { id: 'go-11', category: 'Testing & Benchmarking', phase: 'Applied Practice', title: 'Benchmarks and pprof profiling', status: 'learning', resource_link: '', applied_in_project: '', notes: '' },
  { id: 'go-12', category: 'Tooling', phase: 'Applied Practice', title: 'pprof CPU and heap profiles', status: 'learning', resource_link: '', applied_in_project: '', notes: '' },
  { id: 'go-13', category: 'Cloud/AWS Integration', phase: 'Applied Practice', title: 'AWS SDK v2 clients', status: 'not-started', resource_link: '', applied_in_project: '', notes: '' },
  { id: 'go-14', category: 'Cloud/AWS Integration', phase: 'Production-Ready', title: 'DynamoDB single-table design with Go SDK', status: 'learning', resource_link: '', applied_in_project: 'distributed-systems-lab', notes: '' },
  { id: 'go-15', category: 'Distributed Systems Patterns', phase: 'Production-Ready', title: 'Idempotent consumers', status: 'mastered', resource_link: '', applied_in_project: 'distributed-systems-lab', notes: 'Store and check a durable idempotency key.' },
  { id: 'go-16', category: 'Distributed Systems Patterns', phase: 'Production-Ready', title: 'Circuit breaker and retry with backoff', status: 'not-started', resource_link: '', applied_in_project: '', notes: '' },
]
