import type { BuildOrderProject, CloudProject, GcpJavaProject } from './types'

// ── Tab 1: Cloud Projects ─────────────────────────────────────────
export const seedCloudProjects: CloudProject[] = [
  // Phase 1
  { id: 'cp-1-1', phaseId: 1, serviceName: 'IAM', cloud: 'AWS', icon: '🔐', projectTitle: 'Role-Based Access Controller', difficulty: 'Beginner', status: 'completed', goal: 'Create IAM users, groups, and roles. Attach least-privilege policies. Enable MFA. Test who can do what.', steps: ['Create 3 IAM users: admin, developer, readonly', 'Assign users to groups with different policies', 'Create a role for EC2 to access S3', 'Write a Go script using AWS SDK to assume roles and list resources', 'Try denied actions and read the error details'], hint: 'Use aws-sdk-go-v2 → iam.Client, sts.AssumeRole' },
  { id: 'cp-1-2', phaseId: 1, serviceName: 'IAM', cloud: 'GCP', icon: '🔐', projectTitle: 'Service Account Privilege Lab', difficulty: 'Beginner', status: 'completed', goal: 'Create service accounts with scoped roles. Impersonate them and observe access boundaries across GCP resources.', steps: ['Create 2 service accounts: app-runner and log-viewer', 'Bind roles: roles/storage.objectViewer, roles/logging.viewer', 'Generate JSON keys and authenticate with Go', 'Try accessing a resource outside granted roles', 'Audit using GCP IAM policy analyzer'], hint: 'Use google.golang.org/api/option.WithCredentialsFile' },
  { id: 'cp-1-3', phaseId: 1, serviceName: 'EC2 / Compute Engine', cloud: 'AWS', icon: '🖥', projectTitle: 'Auto-Provisioned Web Server', difficulty: 'Beginner', status: 'in-progress', goal: 'Launch an EC2 instance via CLI/SDK with a startup script that installs and runs a Go HTTP server automatically.', steps: ['Launch t2.micro with Amazon Linux 2 AMI', 'Pass user-data script that installs Go + runs hello server', 'Attach security group allowing port 8080', 'SSH in and verify the process', 'Stop/start instance and observe IP change behavior'], hint: 'Use ec2.RunInstances with UserData base64 encoded script' },
  { id: 'cp-1-4', phaseId: 1, serviceName: 'EC2 / Compute Engine', cloud: 'GCP', icon: '🖥', projectTitle: 'Startup-Script HTTP Server', difficulty: 'Beginner', status: 'in-progress', goal: 'Create a Compute Engine VM using gcloud CLI with a startup script launching a Go server. Explore machine types.', steps: ['Create e2-micro VM via gcloud compute instances create', 'Attach startup-script metadata to install and run Go binary', 'Create firewall rule allowing tcp:8080', 'SSH and tail /var/log/syslog for startup logs', 'Resize machine type and observe restart behavior'], hint: 'Use compute.InstancesClient from google.golang.org/api/compute/v1' },
  { id: 'cp-1-5', phaseId: 1, serviceName: 'S3 / Cloud Storage', cloud: 'AWS', icon: '🗄', projectTitle: 'Static File CDN Uploader', difficulty: 'Beginner', status: 'not-started', goal: 'Build a Go CLI that uploads files to S3, sets public-read ACL, enables versioning, and generates pre-signed URLs.', steps: ['Create a versioned S3 bucket with CLI', 'Write Go CLI: upload file, list versions, download specific version', 'Generate pre-signed URL valid for 5 minutes', 'Enable lifecycle rule to delete versions older than 30 days', 'Test with 3 updates of the same file and restore old version'], hint: 's3.PutObject, s3.GetObject, s3.PresignClient' },
  { id: 'cp-1-6', phaseId: 1, serviceName: 'S3 / Cloud Storage', cloud: 'GCP', icon: '🗄', projectTitle: 'Object Lifecycle Manager', difficulty: 'Beginner', status: 'not-started', goal: 'Create a GCS bucket with lifecycle rules, upload versioned objects, and read them back with signed URLs using Go.', steps: ['Create bucket with Nearline storage class', 'Enable object versioning via Go SDK', 'Upload 3 versions of config.json', 'Set lifecycle rule: archive after 7 days', 'Generate signed URL using service account private key'], hint: 'storage.NewClient, BucketHandle.Object.NewWriter/NewReader' },
  { id: 'cp-1-7', phaseId: 1, serviceName: 'VPC', cloud: 'AWS', icon: '🌐', projectTitle: 'Isolated Network Architecture', difficulty: 'Intermediate', status: 'not-started', goal: 'Build a VPC with public + private subnets across 2 AZs. Deploy a bastion host in public, app server in private.', steps: ['Create VPC with CIDR 10.0.0.0/16', 'Add public subnet (10.0.1.0/24) and private subnet (10.0.2.0/24)', 'Attach Internet Gateway to public subnet', 'Add NAT Gateway in public subnet for private egress', 'SSH to bastion, then jump to private instance'], hint: 'ec2.CreateVpc, CreateSubnet, CreateInternetGateway — chain calls' },
  { id: 'cp-1-8', phaseId: 1, serviceName: 'VPC Network', cloud: 'GCP', icon: '🌐', projectTitle: 'Custom VPC with Firewall Rules', difficulty: 'Intermediate', status: 'not-started', goal: 'Create a custom-mode VPC with regional subnets. Apply firewall rules to allow only specific traffic between VMs.', steps: ['Create custom VPC (no auto-subnets)', 'Add subnet in us-central1 and europe-west1', 'Create firewall rules: allow ssh from your IP only', 'Deploy VM in each region, test cross-region ping', 'Block ICMP between regions via firewall and verify'], hint: 'compute.FirewallsClient, SubnetworksClient' },
  { id: 'cp-1-9', phaseId: 1, serviceName: 'CloudWatch', cloud: 'AWS', icon: '📊', projectTitle: 'Go App Metrics Dashboard', difficulty: 'Intermediate', status: 'not-started', goal: 'Instrument a Go HTTP server to push custom CloudWatch metrics (request count, latency) and build an alarm.', steps: ['Write Go server that publishes custom metrics via PutMetricData', 'Push latency_ms and request_count every 30s', 'Create CloudWatch dashboard with 2 widgets', 'Set alarm: trigger SNS email if latency_ms > 500', 'Simulate high latency and receive alert'], hint: 'cloudwatch.PutMetricData with MetricDatum structs' },
  { id: 'cp-1-10', phaseId: 1, serviceName: 'Cloud Monitoring', cloud: 'GCP', icon: '📊', projectTitle: 'Custom Metrics Alert System', difficulty: 'Intermediate', status: 'not-started', goal: 'Use the GCP Monitoring API to push custom metrics from a Go app and create an alerting policy with notification channel.', steps: ['Create custom metric descriptor: custom.googleapis.com/app/latency', 'Write Go app that writes time-series data every 60s', 'Create a dashboard in GCP Console with your metric', 'Set alert policy: trigger if value > 1000ms for 2 mins', 'Add email notification channel and test firing'], hint: 'monitoring.MetricClient.CreateTimeSeries' },
  // Phase 2
  { id: 'cp-2-1', phaseId: 2, serviceName: 'ECS + Fargate', cloud: 'AWS', icon: '🐳', projectTitle: 'Containerized REST API', difficulty: 'Intermediate', status: 'not-started', goal: 'Dockerize a Go REST API, push to ECR, and deploy to ECS Fargate with auto-scaling based on CPU usage.', steps: ['Write Go REST API with /health and /items endpoints', 'Dockerfile: multi-stage build, final image ~15MB', 'Push to ECR using aws ecr get-login-password', 'Create ECS Cluster → Task Definition → Service on Fargate', 'Add Application Auto Scaling on CPU > 60%'], hint: 'No SDK needed — just CLI deployment. Use gorilla/mux or net/http' },
  { id: 'cp-2-2', phaseId: 2, serviceName: 'GKE', cloud: 'GCP', icon: '🐳', projectTitle: 'K8s Microservice with HPA', difficulty: 'Intermediate', status: 'not-started', goal: 'Deploy a Go service to GKE. Configure Horizontal Pod Autoscaler. Observe pods scaling under load with hey/k6.', steps: ['Create GKE Autopilot cluster', 'Build & push Go image to Artifact Registry', 'Write Deployment and Service YAML (ClusterIP)', 'Configure HPA: min 1, max 5, CPU threshold 50%', 'Run load test with hey -n 10000 and watch kubectl get hpa'], hint: 'k8s.io/client-go to interact with cluster programmatically' },
  { id: 'cp-2-3', phaseId: 2, serviceName: 'Lambda', cloud: 'AWS', icon: '⚡', projectTitle: 'Event-Driven Image Resizer', difficulty: 'Intermediate', status: 'not-started', goal: 'S3 upload triggers a Lambda (Go runtime) that resizes the image and saves thumbnails back to a different S3 prefix.', steps: ['Write Go Lambda handler using aws-lambda-go', 'Build for linux/amd64, zip and deploy', 'Configure S3 event trigger on s3:ObjectCreated:*', 'Use imaging library to resize to 200x200', 'Test: upload a PNG, check thumbnails/ prefix in S3'], hint: 'github.com/aws/aws-lambda-go/lambda + github.com/disintegration/imaging' },
  { id: 'cp-2-4', phaseId: 2, serviceName: 'Cloud Run', cloud: 'GCP', icon: '⚡', projectTitle: 'Serverless URL Shortener', difficulty: 'Intermediate', status: 'not-started', goal: 'Deploy a stateless Go URL shortener service on Cloud Run. Store mappings in Firestore. Auto-scales to zero.', steps: ['Write Go HTTP server: POST /shorten, GET /:code', 'Store {code: originalURL} in Firestore', 'Containerize and push to Artifact Registry', 'Deploy to Cloud Run with --allow-unauthenticated', 'Test cold start latency vs warm request latency'], hint: 'cloud.google.com/go/firestore + net/http, deploy via gcloud run deploy' },
  { id: 'cp-2-5', phaseId: 2, serviceName: 'EKS', cloud: 'AWS', icon: '☸️', projectTitle: 'Multi-Service K8s App', difficulty: 'Advanced', status: 'not-started', goal: 'Deploy a frontend + backend + Redis on EKS. Use ConfigMaps and Secrets. Expose via ALB Ingress Controller.', steps: ['Create EKS cluster with eksctl', 'Deploy Go backend as Deployment + ClusterIP Service', 'Deploy Redis using Helm chart', 'Mount DB_URL as Secret, APP_ENV as ConfigMap', 'Install AWS Load Balancer Controller, create Ingress'], hint: 'Use k8s.io/client-go to read ConfigMaps inside Pod at runtime' },
  { id: 'cp-2-6', phaseId: 2, serviceName: 'Cloud Functions', cloud: 'GCP', icon: '🔧', projectTitle: 'Pub/Sub Log Processor', difficulty: 'Intermediate', status: 'not-started', goal: 'Write a Cloud Function (Go) triggered by Pub/Sub messages. Parse log entries and write summaries to BigQuery.', steps: ['Create Pub/Sub topic: app-logs', 'Write Gen2 Cloud Function with PubSub event trigger', 'Parse JSON log messages in Go handler', 'Insert parsed rows into BigQuery table via streaming API', 'Publish 100 messages and verify rows appear in BQ'], hint: 'functions.CloudEvent handler + cloud.google.com/go/bigquery' },
  { id: 'cp-2-7', phaseId: 2, serviceName: 'ECR + Artifact Registry', cloud: 'Both', icon: '📋', projectTitle: 'Automated Image Build Pipeline', difficulty: 'Intermediate', status: 'not-started', goal: 'Build a Go app locally, push to ECR (AWS) and Artifact Registry (GCP), add vulnerability scanning to both.', steps: ['Create ECR repo and GCP Artifact Registry repo', 'Write Makefile: make build, make push-aws, make push-gcp', 'Enable ECR image scanning on push', 'Enable Artifact Registry vulnerability scanning', 'Compare scan results for the same image'], hint: 'Use docker/docker Go client to build image programmatically' },
  { id: 'cp-2-8', phaseId: 2, serviceName: 'App Engine / Elastic Beanstalk', cloud: 'Both', icon: '🚀', projectTitle: 'Zero-Config Go Web App Deploy', difficulty: 'Beginner', status: 'not-started', goal: 'Deploy the same Go web app to both AWS Elastic Beanstalk and GCP App Engine. Compare configs, limitations, and cold starts.', steps: ['Write Go app: serves /ping, /env, /version', 'Deploy to Elastic Beanstalk: eb init + eb deploy', 'Deploy to App Engine Standard: app.yaml + gcloud app deploy', 'Compare: auto-scaling behavior, deploy times, logs', 'Add a breaking change, redeploy, observe rollback options'], hint: 'Read PORT from env (both platforms inject it differently)' },
  // Phase 3
  { id: 'cp-3-1', phaseId: 3, serviceName: 'RDS / Cloud SQL', cloud: 'Both', icon: '🐘', projectTitle: 'Multi-tenant Postgres API', difficulty: 'Intermediate', status: 'not-started', goal: 'Spin up RDS Postgres (or Cloud SQL). Build a Go CRUD API with connection pooling. Test failover with Multi-AZ.', steps: ['Create RDS Postgres in a private subnet with security group', 'Write Go API: CRUD on /users using database/sql + pgx', 'Add pgx connection pooling: max 10 conns', 'Enable automated backups + point-in-time recovery', 'Simulate Multi-AZ failover and measure downtime'], hint: 'github.com/jackc/pgx/v5/pgxpool for connection pool' },
  { id: 'cp-3-2', phaseId: 3, serviceName: 'DynamoDB / Firestore', cloud: 'Both', icon: '⚡', projectTitle: 'Real-Time Leaderboard', difficulty: 'Intermediate', status: 'not-started', goal: 'Build a game leaderboard with DynamoDB (or Firestore). Use GSI for ranked queries. Write a Go service that updates scores.', steps: ['Design table: PK=gameId, SK=userId, score attribute', 'Create GSI: PK=gameId, SK=score (for top-10 queries)', 'Write Go service: UpdateScore, GetTopN, GetUserRank', 'Test hot partition behavior by hammering one gameId', 'Add DynamoDB Streams (or Firestore listener) to log changes'], hint: 'dynamodb.UpdateItem with ADD expression + Query with ScanIndexForward=false' },
  { id: 'cp-3-3', phaseId: 3, serviceName: 'Redshift / BigQuery', cloud: 'Both', icon: '📊', projectTitle: 'E-Commerce Analytics Pipeline', difficulty: 'Intermediate', status: 'not-started', goal: 'Load sample order data into Redshift/BigQuery. Write SQL analytics queries. Visualize with a Go-generated report.', steps: ['Download NYC taxi dataset (public)', 'Load CSV into Redshift via COPY from S3 (or BQ load job)', 'Write 5 analytical queries: top routes, peak hours, avg fare', 'Create a Go program that runs queries and prints a text table', 'Add a materialized view / persistent derived table for speed'], hint: 'aws/aws-sdk-go-v2/service/redshiftdata or cloud.google.com/go/bigquery' },
  { id: 'cp-3-4', phaseId: 3, serviceName: 'Kinesis / Pub/Sub', cloud: 'Both', icon: '🌊', projectTitle: 'Real-Time Event Stream Processor', difficulty: 'Advanced', status: 'not-started', goal: 'Build a producer that sends click events and a consumer that aggregates counts per page in a 10-second tumbling window.', steps: ['Create Kinesis stream (or Pub/Sub topic) with 2 shards', 'Write Go producer: publish random {page, userId, ts} events', 'Write Go consumer: read from shard, count per page per 10s', 'Print rolling window summary to stdout every 10 seconds', 'Increase producer rate and observe consumer lag'], hint: 'kinesis.PutRecords (batch) + GetShardIterator + GetRecords loop' },
  { id: 'cp-3-5', phaseId: 3, serviceName: 'ElastiCache / Memorystore', cloud: 'Both', icon: '🔴', projectTitle: 'Cache-Aside Pattern API', difficulty: 'Intermediate', status: 'not-started', goal: 'Add Redis caching to a Go REST API. Implement cache-aside: read from Redis, fallback to Postgres, write-back on miss.', steps: ['Deploy ElastiCache Redis (or Memorystore) in VPC', 'Write middleware in Go that checks Redis before DB', 'Cache /products/:id responses with 60s TTL', 'Add cache invalidation on PUT/DELETE', 'Benchmark: 100 requests with vs without cache (use go-wrk)'], hint: 'github.com/redis/go-redis/v9 for Redis client' },
  { id: 'cp-3-6', phaseId: 3, serviceName: 'Glue / Dataflow', cloud: 'Both', icon: '🔄', projectTitle: 'CSV-to-Parquet ETL Job', difficulty: 'Advanced', status: 'not-started', goal: 'Build an ETL that reads CSV from S3/GCS, transforms columns, and writes Parquet files partitioned by date.', steps: ['Upload sample sales CSV to S3 bucket (or GCS)', 'Write Glue PySpark job (or Dataflow Apache Beam job)', 'Transform: parse dates, normalize strings, add computed column', 'Write output as Parquet partitioned by year/month/day', 'Query the Parquet output with Athena or BigQuery external table'], hint: 'For Go: trigger Glue job via glue.StartJobRun SDK call' },
  // Phase 4
  { id: 'cp-4-1', phaseId: 4, serviceName: 'Route 53 / Cloud DNS', cloud: 'Both', icon: '🌍', projectTitle: 'Latency-Based Global Router', difficulty: 'Intermediate', status: 'not-started', goal: 'Deploy Go API servers in 2 regions. Use Route 53 latency routing (or GCP Traffic Director) to route users to nearest region.', steps: ['Deploy same Go API on EC2 in us-east-1 and ap-south-1', 'Register a domain (or use subdomain of existing)', 'Create Route 53 latency records pointing to each region', 'Test from different IP locations using curl with verbose', "Kill one region's server and observe DNS failover behavior"], hint: 'route53.ChangeResourceRecordSets to automate DNS updates' },
  { id: 'cp-4-2', phaseId: 4, serviceName: 'CloudFront / Cloud CDN', cloud: 'Both', icon: '⚡', projectTitle: 'Cached Static Site with Headers', difficulty: 'Intermediate', status: 'not-started', goal: 'Host a static Go-generated HTML site on S3/GCS. Serve via CloudFront/Cloud CDN. Add custom cache-control headers.', steps: ['Generate 100 static HTML pages with a Go program', 'Upload to S3 with public-read (or GCS uniform bucket-level)', 'Create CloudFront distribution with S3 origin + OAC', 'Set Cache-Control: max-age=86400 on .html, no-cache on .json', 'Use curl -I to inspect X-Cache: Hit from cloudfront header'], hint: 'Use html/template to generate pages, s3.PutObjectInput with CacheControl field' },
  { id: 'cp-4-3', phaseId: 4, serviceName: 'ALB / NLB / Cloud Load Balancing', cloud: 'Both', icon: '⚖️', projectTitle: 'Blue-Green Deployment Switch', difficulty: 'Advanced', status: 'not-started', goal: 'Run two versions of a Go API behind an ALB. Shift traffic from v1 (blue) to v2 (green) using weighted target groups.', steps: ['Create 2 EC2 target groups: blue (v1) and green (v2)', 'Create ALB with listener rule: 100% → blue initially', 'Deploy Go v2 to green instances with new /version response', 'Gradually shift: 90/10, 50/50, 0/100 via SDK calls', 'Write Go script that automates the traffic shift loop'], hint: 'elbv2.ModifyRule with WeightedTargetGroup Actions' },
  { id: 'cp-4-4', phaseId: 4, serviceName: 'WAF & Shield / Cloud Armor', cloud: 'Both', icon: '🛡', projectTitle: 'Rate-Limited API with IP Blocklist', difficulty: 'Intermediate', status: 'not-started', goal: 'Attach WAF to an ALB (or Cloud Armor to a Load Balancer). Block specific IPs, rate-limit to 100 req/5min per IP.', steps: ["Create WAF Web ACL with rate-based rule: 100 req/5 min", "Add IP set blocklist with your test machine's IP", 'Attach WAF to ALB (or Cloud Armor security policy to backend)', 'Send burst requests from blocked IP using Apache Bench', 'View WAF sampled requests in console to see blocks'], hint: 'wafv2.CreateWebACL + AssociateWebACL SDK calls' },
  { id: 'cp-4-5', phaseId: 4, serviceName: 'KMS / Cloud KMS', cloud: 'Both', icon: '🔑', projectTitle: 'Envelope Encryption for Config Files', difficulty: 'Advanced', status: 'not-started', goal: 'Use KMS to implement envelope encryption: generate a data key, encrypt a config file locally, store encrypted key in S3.', steps: ['Create KMS symmetric key (or Cloud KMS key ring + key)', 'Use GenerateDataKey to get plaintext + encrypted data key', 'Encrypt config.json with AES-GCM using plaintext data key', 'Store: encrypted config + encrypted data key in S3/GCS', 'Write Go decrypt function: decrypt data key with KMS, then decrypt config'], hint: 'kms.GenerateDataKey + crypto/aes + cipher.NewGCM in stdlib' },
  { id: 'cp-4-6', phaseId: 4, serviceName: 'Secrets Manager / Secret Manager', cloud: 'Both', icon: '🤫', projectTitle: 'Zero Hardcoded Secrets App', difficulty: 'Intermediate', status: 'not-started', goal: 'Refactor a Go app that had hardcoded DB credentials. Fetch all secrets at startup from Secrets Manager with rotation.', steps: ['Create secret: prod/myapp/db with JSON {host, user, pass}', 'Write Go helper: fetchSecret(name) → struct using SDK', 'Fetch secrets at app boot, never from env vars or files', 'Enable automatic rotation (RDS Lambda rotator)', 'Test: manually rotate secret, restart app, verify it still connects'], hint: 'secretsmanager.GetSecretValue, unmarshal JSON into config struct' },
  // Phase 5
  { id: 'cp-5-1', phaseId: 5, serviceName: 'CloudFormation / Terraform', cloud: 'Both', icon: '📐', projectTitle: 'Full VPC Stack as Code', difficulty: 'Intermediate', status: 'not-started', goal: 'Write a CloudFormation template (or Terraform HCL) that provisions a complete VPC, subnets, IGW, NAT, and a bastion EC2.', steps: ['Write CFN template or Terraform: VPC + 2 pub + 2 priv subnets', 'Add Parameters: Env (dev/prod) to switch instance sizes', 'Add Outputs: BastionIP, VPC ID for reference', 'Deploy stack, verify all resources in console', 'Change a CIDR, run changeset/plan, apply and observe'], hint: 'cloudformation.CreateStack + DescribeStackEvents to poll status' },
  { id: 'cp-5-2', phaseId: 5, serviceName: 'CodePipeline / Cloud Build', cloud: 'Both', icon: '🔁', projectTitle: 'Go App CI/CD Pipeline', difficulty: 'Advanced', status: 'not-started', goal: 'Build a full CI/CD: source commit → Go test → Docker build → push to ECR → deploy to ECS (or Cloud Run).', steps: ['Connect GitHub repo to CodePipeline (or Cloud Build trigger)', 'Add build stage: go test ./..., go vet, staticcheck', 'Add Docker build + push to ECR/Artifact Registry stage', 'Add deploy stage: update ECS service or gcloud run deploy', 'Break a test, push, observe pipeline fail + get email alert'], hint: 'Add a Go test that checks HTTP /health returns 200 as integration test' },
  { id: 'cp-5-3', phaseId: 5, serviceName: 'CDK / Terraform (GCP)', cloud: 'Both', icon: '🏗', projectTitle: 'Serverless API with IaC', difficulty: 'Advanced', status: 'not-started', goal: 'Use AWS CDK (TypeScript) or Terraform GCP provider to define a Lambda + API Gateway + DynamoDB table as code.', steps: ['Init CDK app or Terraform module', 'Define: Lambda function, API Gateway HTTP API, DynamoDB table', 'Add IAM role with least-privilege inline policy', 'cdk deploy or terraform apply — watch resource creation', 'cdk diff or terraform plan to preview a change before applying'], hint: 'Lambda Go function code lives in separate Go module inside the CDK project' },
  { id: 'cp-5-4', phaseId: 5, serviceName: 'Systems Manager / Config & Audit', cloud: 'AWS', icon: '🔧', projectTitle: 'Patch & Compliance Automation', difficulty: 'Intermediate', status: 'not-started', goal: 'Use SSM to run commands across EC2 fleet without SSH. Enable AWS Config rules for compliance checks.', steps: ['Install SSM agent on 3 EC2 instances', 'Use Run Command to execute shell scripts across all 3', 'Set up Patch Manager baseline: auto-patch monthly', 'Create AWS Config rule: ec2-instance-no-public-ip', 'View non-compliant resources in Config dashboard'], hint: 'ssm.SendCommand + ListCommandInvocations to poll results' },
  { id: 'cp-5-5', phaseId: 5, serviceName: 'CloudTrail / Security Command Center', cloud: 'Both', icon: '🕵️', projectTitle: 'Security Audit Trail Analyzer', difficulty: 'Advanced', status: 'not-started', goal: 'Enable CloudTrail. Write a Go program that reads trail events, detects unauthorized API calls, and alerts via SNS.', steps: ["Enable CloudTrail multi-region trail to S3 + CloudWatch Logs", "Write Go program: query CloudWatch Logs Insights for denied actions", "Find events where errorCode='AccessDenied'", 'Send summary email via SNS when count > 10 in last hour', 'Simulate denial: try deleting a resource with restricted role'], hint: 'cloudwatchlogs.StartQuery + GetQueryResults polling loop' },
  { id: 'cp-5-6', phaseId: 5, serviceName: 'Cloud Deploy / CodeDeploy', cloud: 'Both', icon: '🚢', projectTitle: 'Canary Release with Auto-Rollback', difficulty: 'Advanced', status: 'not-started', goal: 'Deploy a Go app update using canary strategy: 10% traffic first, verify metrics, then 100% — or rollback automatically.', steps: ['Define deployment config: canary 10%, wait 5 min, 100%', 'Add pre/post deployment Lambda hooks that check /health', 'Write failing health check (return 500) to trigger rollback', 'Observe auto-rollback when hook fails', 'Deploy a working version and watch 10% → 100% progression'], hint: 'codedeploy.CreateDeployment + GetDeployment polling' },
  // Phase 6
  { id: 'cp-6-1', phaseId: 6, serviceName: 'SageMaker / Vertex AI', cloud: 'Both', icon: '🤖', projectTitle: 'Custom Text Classifier Endpoint', difficulty: 'Advanced', status: 'not-started', goal: 'Train a simple text classifier on SageMaker/Vertex AI. Deploy as a real-time endpoint. Call it from a Go service.', steps: ['Use built-in BlazingText (AWS) or AutoML Text (GCP) algorithm', 'Upload labeled CSV dataset to S3/GCS', 'Launch training job via SDK, monitor in console', 'Deploy trained model to endpoint with 1 instance', 'Write Go client: POST text → GET label + confidence score'], hint: 'sagemakerruntime.InvokeEndpoint or aiplatform endpoint prediction REST API' },
  { id: 'cp-6-2', phaseId: 6, serviceName: 'Bedrock / Gemini API', cloud: 'Both', icon: '✨', projectTitle: 'Go-Powered RAG Chatbot', difficulty: 'Advanced', status: 'not-started', goal: 'Build a Retrieval-Augmented Generation chatbot in Go. Store docs in DynamoDB/Firestore, retrieve context, call Bedrock/Gemini.', steps: ['Store 20 product FAQ documents in DynamoDB with embedding field', 'Pre-compute embeddings using Bedrock Titan (or Vertex textembedding)', 'At query time: embed question, find top-3 nearest docs (cosine sim)', 'Build prompt: system + retrieved context + user question', 'Stream response from Claude via Bedrock / Gemini via Go'], hint: 'bedrockruntime.InvokeModelWithResponseStream for streaming responses' },
  { id: 'cp-6-3', phaseId: 6, serviceName: 'Step Functions / Workflows', cloud: 'Both', icon: '🗺', projectTitle: 'Order Processing State Machine', difficulty: 'Advanced', status: 'not-started', goal: 'Model an e-commerce order flow as a state machine: validate → charge → fulfill → notify. Handle failures with retry + catch.', steps: ['Define state machine: 4 Lambda steps + Choice state', 'Add Retry: MaxAttempts=3 for charge step', 'Add Catch: route to Cancel state on payment failure', 'Add Wait state: 24h delay before auto-cancel of unpaid order', 'Trigger via Go SDK and view execution history visually'], hint: 'sfn.StartExecution + GetExecutionHistory to trace state transitions' },
  { id: 'cp-6-4', phaseId: 6, serviceName: 'EventBridge / Eventarc', cloud: 'Both', icon: '📡', projectTitle: 'Event-Driven Microservice Bus', difficulty: 'Advanced', status: 'not-started', goal: 'Connect 3 Go microservices via EventBridge (or Eventarc). Each service publishes and subscribes to typed domain events.', steps: ['Create custom event bus: myapp-bus', 'Service A (Orders): publish OrderPlaced event from Go', 'Service B (Inventory): subscribe to OrderPlaced, reduce stock', 'Service C (Notifications): subscribe to OrderPlaced, send email', 'Add schema validation on event bus to catch bad payloads'], hint: 'eventbridge.PutEvents with DetailType and Source fields' },
  { id: 'cp-6-5', phaseId: 6, serviceName: 'Athena / BigQuery External Tables', cloud: 'Both', icon: '🔍', projectTitle: 'Serverless Log Analytics Platform', difficulty: 'Intermediate', status: 'not-started', goal: 'Store application logs as JSON in S3/GCS. Query with Athena/BigQuery. Build a Go CLI report tool.', steps: ['Write Go app that dumps structured JSON logs to S3/GCS', 'Create Glue Crawler (or BQ external table) over log prefix', 'Write 5 Athena/BQ queries: errors by hour, top endpoints, p99 latency', 'Schedule queries with EventBridge rule (or Cloud Scheduler)', 'Go CLI: fetch query results and render ASCII table'], hint: 'athena.StartQueryExecution + GetQueryResults pagination' },
  { id: 'cp-6-6', phaseId: 6, serviceName: 'AWS Organizations / GCP Resource Manager', cloud: 'Both', icon: '🏢', projectTitle: 'Multi-Account Landing Zone', difficulty: 'Advanced', status: 'not-started', goal: 'Create an AWS Organization with 3 OUs (dev/staging/prod). Apply SCPs to restrict regions. Mirror in GCP with folder hierarchy.', steps: ['Create AWS Org, enable all features', 'Create OUs: dev, staging, prod with child accounts', 'Apply SCP: DenyRegionsOutsideUSEast1 to dev OU', 'Create GCP folder hierarchy: org → env folders → projects', 'Apply org policy: constraints/compute.restrictCloudRunRegions'], hint: 'organizations.CreateAccount + AttachPolicy via SDK' },
]

// ── Tab 2: AWS Build Order ─────────────────────────────────────────
export const seedBuildOrder: BuildOrderProject[] = [
  { id: 1,  phase: 'small',        title: 'IAM roles & policies sandbox',            services: ['IAM'],                                                           go: 'not-required', goNote: 'Console/CLI config only — no application code.',                                           libs: [],                                                                                                                                                                                                     desc: 'Create least-privilege roles for a Lambda, an EC2 instance, and a CI/CD pipeline; test what breaks with overly restrictive policies.', done: false },
  { id: 2,  phase: 'small',        title: 'VPC from scratch',                         services: ['VPC', 'Security Groups', 'NAT Gateway'],                         go: 'not-required', goNote: 'Console/CLI config only — no application code.',                                           libs: [],                                                                                                                                                                                                     desc: 'Public + private subnets, bastion host, NAT for outbound-only private access. Pure networking, sets up the foundation later projects deploy into.', done: false },
  { id: 3,  phase: 'small',        title: 'S3 + Lambda image processor',              services: ['S3', 'Lambda', 'IAM'],                                           go: 'required',     goNote: 'Lambda function on the provided.al2023 runtime.',                                          libs: ['github.com/aws/aws-lambda-go/lambda', 'github.com/aws/aws-sdk-go-v2/service/s3'],                                                                                                                    desc: 'Upload product images, auto-generate thumbnails on an S3 event trigger.', done: false },
  { id: 4,  phase: 'small',        title: 'DynamoDB product catalog',                 services: ['DynamoDB', 'IAM'],                                               go: 'required',     goNote: 'Standalone Go service, no Lambda needed.',                                                 libs: ['github.com/aws/aws-sdk-go-v2/service/dynamodb', 'github.com/aws/aws-sdk-go-v2/config'],                                                                                                              desc: 'Single-table design with GSIs for category and price lookups.', done: false },
  { id: 5,  phase: 'small',        title: 'SQS order queue',                          services: ['SQS', 'IAM'],                                                    go: 'required',     goNote: 'Go producer/consumer instead of Lambda.',                                                  libs: ['github.com/aws/aws-sdk-go-v2/service/sqs'],                                                                                                                                                          desc: 'Decouple order placement from inventory deduction; add a DLQ for failed orders.', done: false },
  { id: 6,  phase: 'small',        title: 'CloudWatch alarms + SNS',                  services: ['CloudWatch', 'SNS', 'IAM'],                                      go: 'optional',     goNote: 'Only needed if pushing custom metrics from your app.',                                      libs: ['github.com/aws/aws-sdk-go-v2/service/cloudwatch'],                                                                                                                                                    desc: 'Alerting pipeline for your existing Go service — error rate and latency thresholds.', done: false },
  { id: 7,  phase: 'small',        title: 'Secrets Manager + Lambda',                 services: ['Secrets Manager', 'Lambda', 'IAM'],                              go: 'required',     goNote: 'Lambda function.',                                                                         libs: ['github.com/aws/aws-lambda-go/lambda', 'github.com/aws/aws-sdk-go-v2/service/secretsmanager'],                                                                                                        desc: 'Rotate and fetch DB credentials instead of hardcoding env vars.', done: false },
  { id: 8,  phase: 'intermediate',  title: 'ECS Fargate deployment',                  services: ['ECS', 'Fargate', 'ALB', 'VPC', 'ECR', 'IAM'],                   go: 'required',     goNote: 'Your existing Go backend, containerized — no new SDK code, just a Dockerfile.',          libs: [],                                                                                                                                                                                                     desc: 'Containerize your Go backend, deploy behind a load balancer inside the VPC from step 2.', done: false },
  { id: 9,  phase: 'intermediate',  title: 'RDS Multi-AZ + read replica',             services: ['RDS', 'VPC', 'Security Groups', 'IAM'],                          go: 'required',     goNote: 'Go service connecting to Postgres.',                                                       libs: ['github.com/jackc/pgx/v5'],                                                                                                                                                                            desc: 'Deploy Postgres with failover and a read replica; connect the ECS Go service from step 8.', done: false },
  { id: 10, phase: 'intermediate',  title: 'API Gateway + Lambda + RDS Proxy',        services: ['API Gateway', 'Lambda', 'RDS Proxy', 'RDS', 'VPC', 'IAM'],      go: 'required',     goNote: 'Lambda function.',                                                                         libs: ['github.com/aws/aws-lambda-go/lambda', 'github.com/aws/aws-lambda-go/events', 'github.com/jackc/pgx/v5'],                                                                                             desc: 'Serverless order API; compare cold-start latency against the ECS setup from step 8.', done: false },
  { id: 11, phase: 'intermediate',  title: 'SNS fan-out inventory sync',              services: ['SNS', 'SQS', 'IAM'],                                             go: 'required',     goNote: 'Go publisher + multiple Go consumers.',                                                    libs: ['github.com/aws/aws-sdk-go-v2/service/sns', 'github.com/aws/aws-sdk-go-v2/service/sqs'],                                                                                                              desc: 'Stock change triggers parallel queues — warehouse, analytics, notifications.', done: false },
  { id: 12, phase: 'intermediate',  title: 'ElastiCache (Redis) cart service',        services: ['ElastiCache', 'VPC', 'ECS', 'IAM'],                              go: 'required',     goNote: 'Standalone Go service.',                                                                   libs: ['github.com/redis/go-redis/v9'],                                                                                                                                                                       desc: 'Cart persistence with TTL, deployed inside your private subnet.', done: false },
  { id: 13, phase: 'intermediate',  title: 'DynamoDB Streams → Lambda audit log',     services: ['DynamoDB Streams', 'Lambda', 'CloudWatch', 'IAM'],               go: 'required',     goNote: 'Lambda function.',                                                                         libs: ['github.com/aws/aws-lambda-go/lambda', 'github.com/aws/aws-lambda-go/events', 'github.com/aws/aws-sdk-go-v2/service/dynamodb'],                                                                       desc: 'Real-time inventory audit trail whenever the stock table changes.', done: false },
  { id: 14, phase: 'intermediate',  title: 'CloudFront + S3 static catalog',          services: ['CloudFront', 'S3', 'IAM'],                                       go: 'optional',     goNote: 'Only for the backing API — CloudFront and S3 themselves need no code.',                   libs: [],                                                                                                                                                                                                     desc: 'CDN-backed product listing page with cache invalidation on updates.', done: false },
  { id: 15, phase: 'intermediate',  title: 'CDK / CloudFormation rewrite',            services: ['CloudFormation', 'CDK'],                                         go: 'optional',     goNote: 'Only if you choose CDK and write it in Go instead of YAML/TypeScript.',                   libs: ['github.com/aws/aws-cdk-go/awscdk/v2'],                                                                                                                                                                desc: 'Pick two earlier projects — suggest steps 3 and 8 — and redeploy entirely via infrastructure-as-code.', done: false },
]

// ── Tab 3: GCP × Java Path ────────────────────────────────────────
export const seedGcpJava: GcpJavaProject[] = [
  { id: 'gj-01', phaseId: 'P.01', title: 'Product Image Pipeline',       flow: 'Storage → Cloud Function → Firestore',                                              teaches: 'Event-triggered compute, object lifecycle, document writes.',                                                               chips: ['Cloud Storage', 'Cloud Functions', 'Firestore'],                                  javaLevel: 'core',     done: false },
  { id: 'gj-02', phaseId: 'P.01', title: 'Order Notification Service',   flow: 'Cloud Run → Pub/Sub → Cloud Run',                                                   teaches: 'Async messaging, push subscriptions, secret handling.',                                                                     chips: ['Cloud Run', 'Pub/Sub', 'Secret Manager'],                                         javaLevel: 'core',     done: false },
  { id: 'gj-03', phaseId: 'P.01', title: 'Product Catalog API',          flow: 'Cloud Run + Cloud SQL ← IAM',                                                       teaches: 'Managed DB connections, least-privilege service accounts.',                                                                 chips: ['Cloud Run', 'Cloud SQL', 'IAM'],                                                  javaLevel: 'core',     done: false },
  { id: 'gj-04', phaseId: 'P.02', title: 'Inventory Event Pipeline',     flow: 'Pub/Sub → Cloud Run consumer → Cloud SQL + BigQuery',                               teaches: 'Dual-sink fan-out, write-time analytics. BigQuery sink is config, not code.',                                              chips: ['Pub/Sub', 'Cloud Run', 'Cloud SQL', 'BigQuery'],                                  javaLevel: 'core',     done: false },
  { id: 'gj-05', phaseId: 'P.02', title: 'Order Processing on GKE',      flow: '2–3 services on GKE, Cloud SQL, Pub/Sub, Secret Manager, Monitoring',               teaches: 'Container orchestration, service-to-service auth, dashboards & alerts. Monitoring setup is YAML/console, not Java.',     chips: ['GKE', 'Cloud SQL', 'Pub/Sub', 'Secret Manager', 'Cloud Monitoring'],              javaLevel: 'core',     done: false },
  { id: 'gj-06', phaseId: 'P.02', title: 'Resilient Checkout Service',   flow: 'Cloud Run + Cloud Tasks + Cloud SQL + VPC + Load Balancing',                        teaches: 'Retry queues, private networking, traffic distribution. VPC and LB are network config, no code.',                         chips: ['Cloud Run', 'Cloud Tasks', 'Cloud SQL', 'VPC', 'Load Balancing'],                  javaLevel: 'core',     done: false },
  { id: 'gj-07', phaseId: 'P.03', title: 'IaC Retrofit',                 flow: "Rebuild Project 05's infra in Terraform",                                           teaches: 'Declarative infra, state management, drift detection.',                                                                     chips: ['Terraform', 'GKE (reused)'],                                                      javaLevel: 'none',     done: false },
  { id: 'gj-08', phaseId: 'P.03', title: 'Simple Data Pipeline',         flow: 'Pub/Sub → Dataflow → BigQuery, run by Cloud Composer',                              teaches: "Stream/batch transforms, DAG orchestration. Beam's Python SDK is faster here; use Java only for SDK practice.",           chips: ['Pub/Sub', 'Dataflow', 'BigQuery', 'Cloud Composer'],                              javaLevel: 'optional', done: false },
  { id: 'gj-09', phaseId: 'P.03', title: 'Two-Region Failover Drill',    flow: 'Cloud CDN + second region + manual failover on Project 03 or 06',                   teaches: 'Multi-region deploys, failover behavior, edge caching.',                                                                    chips: ['Cloud CDN', 'Multi-region deploy'],                                               javaLevel: 'none',     done: false },
]
