/* eslint-disable react-refresh/only-export-components */
import { createContext, useCallback, useContext, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { seedJavaTopics } from './data'
import type { JavaTopic } from './types'
type NewTopic = Omit<JavaTopic, 'id'>; type Value = { topics: JavaTopic[]; addTopic: (t: NewTopic) => void; updateTopic: (id: string, t: NewTopic) => void; patchTopic: (id: string, p: Partial<JavaTopic>) => void; deleteTopic: (id: string) => void }; const Context = createContext<Value | null>(null); let ids = 0
export function JavaStudyProvider({ children }: { children: ReactNode }) { const [topics, setTopics] = useState(seedJavaTopics); const addTopic = useCallback((t: NewTopic) => setTopics(x => [{ ...t, id: `java-${Date.now().toString(36)}-${ids++}` }, ...x]), []); const updateTopic = useCallback((id: string, t: NewTopic) => setTopics(x => x.map(v => v.id === id ? { ...t, id } : v)), []); const patchTopic = useCallback((id: string, p: Partial<JavaTopic>) => setTopics(x => x.map(v => v.id === id ? { ...v, ...p } : v)), []); const deleteTopic = useCallback((id: string) => setTopics(x => x.filter(v => v.id !== id)), []); const value = useMemo(() => ({ topics, addTopic, updateTopic, patchTopic, deleteTopic }), [topics, addTopic, updateTopic, patchTopic, deleteTopic]); return <Context.Provider value={value}>{children}</Context.Provider> }
export function useJavaStudy() { const value = useContext(Context); if (!value) throw new Error('useJavaStudy must be used inside JavaStudyProvider'); return value }
export function useJavaStudySummary() { const { topics } = useJavaStudy(); return useMemo(() => { const done = topics.filter(t => t.status === 'mastered').length; const active = topics.filter(t => t.status === 'learning' || t.status === 'practiced').length; return { progress: topics.length ? Math.round(done / topics.length * 100) : 0, done, active, left: topics.length - done - active } }, [topics]) }
