import type { InterviewTrack, Topic, TopicPhase, TopicPriority } from './types'

// [phase, title, subtopic?] — priority derives from phase; Intermediate projects drop to P2.
type Row = [TopicPhase, string, string?]
const PHASE_PRIORITY: Record<TopicPhase, TopicPriority> = { revise: 'P0', learning: 'P1', projects: 'P1', confident: 'P1', continue: 'P2' }
const seed = (prefix: string, track: InterviewTrack, rows: Row[]): Topic[] => rows.map(([phase, title, subtopic = ''], i) => ({
  id: `${prefix}-${i + 1}`, track, phase, title, subtopic,
  priority: phase === 'projects' && subtopic === 'Intermediate' ? 'P2' : PHASE_PRIORITY[phase],
  status: 'not-started', notes: '', last_studied_date: '',
}))

export const seedTopics: Topic[] = [
  ...seed('jg', 'Java·GCP', [
    ['revise', 'Core Java: collections internals (ArrayList/HashMap growth), generics, exceptions'],
    ['revise', 'OOP + equals/hashCode contract, immutability, records, sealed classes'],
    ['revise', 'Streams API + lambdas — rewrite 5 old solutions using streams'],
    ['learning', 'Concurrency deep: ExecutorService, CompletableFuture, virtual threads (Java 21)'],
    ['learning', 'Concurrency internals: locks, atomics, happens-before, ConcurrentHashMap'],
    ['learning', 'JVM internals: GC algorithms, JIT, memory areas, basic tuning flags'],
    ['learning', 'Spring internals: bean lifecycle, DI mechanics, transaction propagation, AOP'],
    ['learning', 'JPA pitfalls: N+1, lazy loading traps, connection pooling (HikariCP)'],
    ['learning', 'Kafka with Java: producers/consumers, consumer groups, offsets, exactly-once'],
    ['learning', 'Design patterns in Java: factory, strategy, builder, observer, singleton pitfalls'],
    ['learning', 'GCP core: IAM, Cloud Storage, Cloud Run, Pub/Sub, Firestore, Cloud SQL'],
    ['learning', 'GCP×Java artifact projects 1–3 (beginner tier)'],
    ['learning', 'GCP×Java artifact projects 4–6 (GKE, Secret Manager, multi-service)'],
    ['projects', 'CLI expense tracker: collections, streams, records, file I/O, unit tests', 'Beginner'],
    ['projects', 'Spring Boot CRUD API + Cloud SQL, deployed on Cloud Run', 'Beginner'],
    ['projects', 'Order-processing service: Pub/Sub consumer + Firestore, with idempotency + retry handling', 'Intermediate'],
    ['projects', 'Kafka pipeline: producer + consumer group with offset management and a poison-pill strategy', 'Intermediate'],
    ['projects', 'Multi-service deploy on GKE with Secret Manager + health probes (your artifact project 6)', 'Intermediate'],
    ['confident', 'Explain GC choice + JVM tuning for a high-throughput service, cold'],
    ['confident', 'Explain Kafka consumer rebalancing + Pub/Sub redelivery failure modes aloud'],
    ['confident', 'Walk through Spring transaction propagation scenarios without notes'],
    ['confident', 'Deploy + defend one GCP×Java project end-to-end in design-review format'],
    ['continue', 'One GCP service deep-dive per month'],
    ['continue', 'Track Java LTS + Spring release notes quarterly'],
  ]),
  ...seed('ga', 'Go·AWS', [
    ['revise', 'Slices/maps internals: growth, backing arrays, map iteration randomness'],
    ['revise', 'Structs, interfaces (implicit satisfaction, nil interface trap), error idioms'],
    ['revise', 'Goroutines + channels basics: select, buffered vs unbuffered, closing rules'],
    ['revise', 'Re-read ANF code module by module — explain each aloud'],
    ['learning', 'Runtime internals: GMP scheduler model, GC, stack growth'],
    ['learning', 'Context patterns: cancellation, timeouts, goroutine lifecycle ownership'],
    ['learning', 'Concurrency patterns: worker pools, fan-in/out, pipelines, errgroup, semaphores, rate limiting'],
    ['learning', 'API design: versioning, pagination, idempotency keys, rate limiting, error contracts'],
    ['learning', 'gRPC + protobuf: services, streaming, interceptors'],
    ['learning', 'Resilience patterns: idempotency, retries/backoff, circuit breakers, outbox (your e-commerce study)'],
    ['learning', 'Testing depth: table tests, benchmarks, race detector, pprof'],
    ['learning', 'Observability: OpenTelemetry, Prometheus metrics, structured logging (slog)'],
    ['learning', 'AWS core: IAM, VPC, S3, Lambda, ECS + EKS/Kubernetes basics'],
    ['learning', 'Data layer: RDS + pgx/v5, go-redis, SQS/SNS, DynamoDB'],
    ['learning', 'AWS×Go artifact projects 1–7, then 8–15'],
    ['learning', 'Terraform: state, modules, plan/apply — retrofit one project as IaC'],
    ['projects', 'CLI tool: flags, JSON parsing, proper error wrapping, table tests', 'Beginner'],
    ['projects', 'URL shortener API: net/http + DynamoDB, deployed on Lambda (aws-lambda-go)', 'Beginner'],
    ['projects', 'S3 file processor: upload, presigned URLs, event-triggered handling', 'Beginner'],
    ['projects', 'Worker-pool CSV/image processor fed by SQS: errgroup, graceful shutdown, backpressure', 'Intermediate'],
    ['projects', 'gRPC inventory service: protobuf, pgx/v5, Redis cache-aside, interceptors', 'Intermediate'],
    ['projects', 'ANF-style checkout slice: outbox pattern + idempotency keys, hand-written (no Claude Code)', 'Intermediate'],
    ['projects', 'Terraform-provisioned stack: VPC + ECS/EKS service + RDS, one repo, plan/apply discipline', 'Intermediate'],
    ['confident', "Answer 'this Go service leaks memory' — pprof-first workflow, cold"],
    ['confident', 'Explain GMP scheduling + goroutine lifecycle like a design review'],
    ['confident', 'Design ANF-style checkout with outbox + idempotency on AWS, verbally'],
    ['confident', 'Cost-optimization story: one project, written analysis, 3 savings levers'],
    ['continue', '1 Go kata/week; read one stdlib package source per month'],
    ['continue', 'AWS release-notes scan monthly'],
  ]),
  ...seed('cs', 'C#.NET·Azure', [
    ['revise', 'C# after the gap: LINQ (IEnumerable vs IQueryable), async/await, delegates, generics'],
    ['revise', 'ASP.NET Core Web API — shift from MVC-era to minimal APIs + middleware pipeline'],
    ['revise', '.NET runtime: CLR, GC generations, value vs reference, Span<T> awareness'],
    ['learning', '.NET 8/9 features; Task vs Thread, ConfigureAwait, async state machine'],
    ['learning', 'EF Core + DI lifetimes (transient/scoped/singleton) and their traps'],
    ['learning', 'SOLID + design patterns as asked in .NET shops'],
    ['learning', 'Auth: JWT/OAuth2/OpenID Connect in ASP.NET Core'],
    ['learning', 'Azure core: App Service, Functions, Azure SQL, Blob, Cosmos DB basics'],
    ['learning', 'Azure depth: Service Bus, Key Vault, Entra ID, AKS + API Management basics'],
    ['projects', 'Minimal API CRUD + EF Core + Azure SQL, deployed on App Service', 'Beginner'],
    ['projects', 'Azure Function: queue-triggered worker with Blob Storage output', 'Beginner'],
    ['projects', 'Order worker: Service Bus + retries/dead-letter + Key Vault secrets', 'Intermediate'],
    ['projects', 'JWT-secured API: role-based auth, middleware pipeline, rate limiting', 'Intermediate'],
    ['confident', 'Explain async/await state machine + middleware pipeline aloud'],
    ['confident', 'Design a multi-tier web API on Azure verbally, incl. auth + scaling'],
    ['confident', "'8 years .NET → Go → returning' modernization narrative, polished"],
    ['continue', 'Monthly C# refresh; follow .NET release notes'],
  ]),
  ...seed('py', 'Python', [
    ['revise', 'Core syntax: comprehensions, dicts/sets, slicing, f-strings'],
    ['revise', 'Functions, *args/**kwargs, closures, decorators'],
    ['revise', 'Environments + tooling: venv, pip, project layout'],
    ['learning', 'OOP depth: dunder methods, dataclasses, ABCs, protocols'],
    ['learning', 'Generators, iterators, context managers, functools/itertools'],
    ['learning', 'Typing + mypy; asyncio fundamentals'],
    ['learning', 'FastAPI + SQLAlchemy: one REST API with real DB (your stated gap)'],
    ['learning', 'pytest: fixtures, parametrize, mocking'],
    ['learning', 'Profiling basics (cProfile) + one worker/queue concept (Celery or RQ)'],
    ['projects', 'Upgrade one of your existing utilities: add typing, pytest suite, proper packaging', 'Beginner'],
    ['projects', 'FastAPI notes API: SQLAlchemy + SQLite, CRUD, pydantic validation', 'Beginner'],
    ['projects', 'FastAPI + Postgres service with async endpoints + background worker (Celery/RQ)', 'Intermediate'],
    ['projects', 'ETL pipeline: scrape/ingest → transform → load, with tests and cProfile pass', 'Intermediate'],
    ['confident', 'Explain GIL + async vs threads vs multiprocessing trade-offs aloud'],
    ['confident', 'Walk through your FastAPI service end-to-end, interview format'],
    ['confident', 'Use Python comfortably as fallback in live scripting rounds'],
    ['continue', 'One small utility/month; one advanced topic/month'],
  ]),
  ...seed('cc', 'Claude Code', [
    ['revise', 'Audit your current workflow: how you actually use it across ANF, DiagnoCare, Akshar Shiksha'],
    ['revise', 'Review + rewrite your CLAUDE.md files — make context engineering deliberate'],
    ['learning', 'Architecture: the agentic loop — context window, tool use, permissions model'],
    ['learning', 'MCP: what servers are, how tools are exposed, when to build one'],
    ['learning', 'Advanced features: subagents, hooks, skills, custom slash commands'],
    ['learning', 'Headless/CI usage: your GitHub Actions mobile-trigger workflow, productionized'],
    ['learning', 'Spec-driven development: plan → implement → verify loops instead of vibe prompts'],
    ['learning', 'Claude Agent SDK basics: where Claude Code ends and SDK begins'],
    ['learning', 'Agentic AI concepts: RAG end-to-end, evals (LLM-as-judge), guardrails'],
    ['projects', 'Rewrite CLAUDE.md for one repo + build 2 custom slash commands you actually reuse', 'Beginner'],
    ['projects', 'Ship one small feature fully spec-driven: written plan → implement → verify loop', 'Beginner'],
    ['projects', 'Build a simple MCP server (e.g., DiagnoCare MySQL read-only tools) and use it in a session', 'Intermediate'],
    ['projects', 'Productionize your GitHub Actions mobile-trigger workflow: guardrails, review gate, rollback', 'Intermediate'],
    ['projects', 'Mini RAG service: ingestion → retrieval → generation with an eval harness scoring answers', 'Intermediate'],
    ['confident', 'The judgment story: what you always verify, never delegate, how you review AI code'],
    ['confident', 'Pick one AI-built ANF module — explain every line as if you wrote it'],
    ['confident', 'Explain testing + review strategy for AI-generated code in interview format'],
    ['confident', '3 AI-flavored designs aloud: LLM serving, RAG service, agent safeguards'],
    ['confident', "Answer 'won't AI replace engineers?' with a calm, senior, experience-based take"],
    ['continue', 'Track Claude Code release notes monthly; refine CLAUDE.md files'],
    ['continue', 'Biweekly agentic AI scan (evals, SDK changes, new patterns)'],
    ['continue', 'One deliberate workflow experiment per month (new hook, skill, or MCP server)'],
  ]),
  ...seed('re', 'React', [
    ['revise', 'Core React: components, props/state, controlled inputs, lists + keys'],
    ['revise', 'Hooks: useState, useEffect (dependency pitfalls), useRef, useMemo, useCallback'],
    ['revise', 'Rendering mental model: why re-renders happen, reconciliation basics'],
    ['learning', 'TypeScript + React: typing props, generics in components, discriminated unions'],
    ['learning', 'TanStack Query: server state, caching, invalidation, mutations — apply in DiagnoCare'],
    ['learning', 'Zustand for client state; server-state vs client-state boundary'],
    ['learning', 'Tailwind fluency + shadcn/ui component patterns'],
    ['learning', 'Forms: react-hook-form + zod validation'],
    ['learning', 'Routing: TanStack Router or React Router v7 — one, properly'],
    ['learning', 'Performance: memo, code-splitting, list virtualization, React DevTools profiling'],
    ['projects', 'Rebuild one Akshar Shiksha screen hand-written: TypeScript + Tailwind, no AI assist', 'Beginner'],
    ['projects', 'Form flow with react-hook-form + zod: validation, error states, submit handling', 'Beginner'],
    ['projects', 'DiagnoCare feature with TanStack Query + Zustand: list, mutations, cache invalidation', 'Intermediate'],
    ['projects', 'Performance pass on a heavy screen: profile, memoize, virtualize a long list', 'Intermediate'],
    ['confident', 'Explain server vs client state and your caching strategy aloud'],
    ['confident', 'Ship one polished modern-stack feature in Akshar Shiksha, end-to-end, hand-written'],
    ['confident', "Live code-review talk-through of a React component: what you'd fix and why"],
    ['confident', 'Explain a re-render performance fix you actually made'],
    ['continue', 'Monthly ecosystem scan (React releases, TanStack, RSC direction)'],
    ['continue', 'Every new app feature uses the modern stack — no falling back'],
  ]),
  ...seed('db', 'Database', [
    ['revise', 'SQL core: joins, aggregations, subqueries, window functions'],
    ['revise', 'Schema basics: normalization, keys, constraints — review your DiagnoCare 10-table schema'],
    ['revise', 'Transactions 101: ACID, commit/rollback, basic locking intuition'],
    ['learning', 'Indexing deep: B-tree mechanics, composite + covering indexes, when indexes hurt writes'],
    ['learning', 'Query optimization: reading EXPLAIN/EXPLAIN ANALYZE, join strategies, stats'],
    ['learning', 'Isolation levels + anomalies: dirty/non-repeatable/phantom reads, MVCC, deadlocks'],
    ['learning', 'Postgres specifics: VACUUM, connection pooling (PgBouncer), JSONB (your PG16 Cookbook)'],
    ['learning', 'Replication: primary/replica, replication lag, read-your-writes problem, failover'],
    ['learning', 'Scaling concepts: partitioning vs sharding, hot keys, denormalization trade-offs'],
    ['learning', 'NoSQL modeling: Redis patterns (cache-aside, TTL, invalidation), DynamoDB/Firestore single-table thinking'],
    ['learning', 'SQL vs NoSQL decision framework: consistency, access patterns, query flexibility'],
    ['projects', 'Schema build: design + seed a realistic domain (DiagnoCare-style) with constraints, then break them deliberately', 'Beginner'],
    ['projects', 'Index lab: write 5 slow queries, read EXPLAIN, fix each with the right index — measure before/after', 'Beginner'],
    ['projects', 'Concurrency lab: reproduce a deadlock + isolation anomalies with two sessions, then fix', 'Intermediate'],
    ['projects', 'Replication lab: primary/replica Postgres in Docker, measure lag, practice failover', 'Intermediate'],
    ['confident', 'Explain isolation levels + their anomalies aloud, with examples'],
    ['confident', 'Live-debug a slow query: EXPLAIN → diagnose → fix, narrated'],
    ['confident', 'SQL vs NoSQL recommendation for a given workload, with trade-offs, cold'],
    ['confident', 'Explain how a B-tree index works from disk pages up'],
    ['continue', 'One query-tuning exercise per month'],
    ['continue', 'Postgres release highlights, yearly scan'],
  ]),
  ...seed('do', 'DevOps', [
    ['revise', 'Linux essentials: processes, permissions, systemd, logs, grep/awk/sed for debugging'],
    ['revise', 'Git workflows: branching strategies, rebase vs merge, protected branches'],
    ['revise', 'Networking for ops: ports, DNS resolution, curl-driven HTTP debugging'],
    ['revise', 'HTTP/REST semantics: methods, status codes, headers, caching'],
    ['learning', 'Networking depth: TCP vs UDP, TLS handshake, DNS, L4 vs L7 load balancing'],
    ['learning', 'OS basics: processes vs threads, memory paging, file descriptors'],
    ['learning', 'Docker deep: images vs containers, layers, multi-stage builds, compose, image slimming'],
    ['learning', 'Container internals: namespaces + cgroups — what a container actually is'],
    ['learning', 'Kubernetes core: pods, deployments, services, ingress, ConfigMaps/Secrets'],
    ['learning', 'Kubernetes ops: liveness/readiness probes, resource requests/limits, HPA'],
    ['learning', 'CI/CD with GitHub Actions: test → build → deploy pipelines, environments, approvals'],
    ['learning', 'Terraform depth: modules, remote state, workspaces, drift detection'],
    ['learning', 'Deployment strategies: rolling, blue-green, canary — and rollback for each'],
    ['projects', 'Dockerize one of your apps: multi-stage build, slim image, compose with its DB', 'Beginner'],
    ['projects', 'GitHub Actions pipeline: lint → test → build → push image, with a status badge', 'Beginner'],
    ['projects', 'Deploy a service to Kubernetes (kind locally or GKE): deployment, service, ingress, probes, HPA', 'Intermediate'],
    ['projects', 'Full IaC pipeline: Terraform + Actions deploying to cloud, with plan-review gate + rollback path', 'Intermediate'],
    ['confident', "Explain a request's full journey: DNS → TLS → LB → service → DB, aloud"],
    ['confident', 'Explain what a container is from kernel primitives up, aloud'],
    ['confident', "Debug 'pod stuck in CrashLoopBackOff' scenario, cold — a classic interview drill"],
    ['confident', 'Design a CI/CD pipeline verbally, including rollback and secrets handling'],
    ['confident', 'Canary vs blue-green recommendation for a given service, with trade-offs'],
    ['continue', 'One Kubernetes concept deep-dive per month'],
    ['continue', 'Monthly networking refresher question set'],
    ['continue', "Keep both apps' pipelines green — your living DevOps portfolio"],
  ]),
  ...seed('se', 'Security', [
    ['revise', 'AuthN vs AuthZ; sessions vs tokens — where each fits'],
    ['revise', 'Hashing vs encryption vs encoding; why bcrypt/argon2 for passwords'],
    ['revise', 'HTTPS/TLS role; why secrets never live in code or git history'],
    ['learning', 'OWASP Top 10 with examples: injection, XSS, CSRF, SSRF, broken access control'],
    ['learning', 'SQL injection prevention: parameterized queries, ORM pitfalls'],
    ['learning', 'JWT deep: claims, expiry, refresh tokens, common misuses'],
    ['learning', 'OAuth2 + OIDC flows: auth code + PKCE, client credentials — when each applies'],
    ['learning', 'Secrets management: cloud secret managers (Secret Manager/Key Vault/KMS), rotation'],
    ['learning', 'IAM least privilege across AWS/GCP; service accounts vs user creds'],
    ['learning', 'Supply chain basics: dependency scanning, lockfiles, image scanning'],
    ['projects', 'Harden one API: input validation, parameterized queries, security headers, rate limiting', 'Beginner'],
    ['projects', 'Implement full JWT auth: login, refresh rotation, logout/revocation', 'Beginner'],
    ['projects', 'Threat-model DiagnoCare (STRIDE-lite): patient data flows, top 3 risks, fix them', 'Intermediate'],
    ['projects', 'Secrets migration: hardcoded/env creds → cloud secret manager with rotation', 'Intermediate'],
    ['confident', 'Explain the OAuth2 auth-code + PKCE flow aloud, no notes'],
    ['confident', 'SQLi, XSS, CSRF: attack + prevention for each, cold'],
    ['confident', 'Walk through your DiagnoCare threat model like a security review'],
    ['confident', 'Explain your password storage design and defend every choice'],
    ['continue', 'Monthly OWASP question set'],
    ['continue', 'Dependency + image scan habit on both apps'],
  ]),
  ...seed('mo', 'Monitoring', [
    ['revise', 'Current state audit: what logging/metrics your apps and ANF services actually have'],
    ['revise', 'Metrics vs logs vs traces — what question each answers'],
    ['learning', 'Structured logging: levels, request IDs, correlation across services'],
    ['learning', 'Prometheus model: counters, gauges, histograms; scraping + cardinality traps'],
    ['learning', 'Golden signals: latency, traffic, errors, saturation — per service'],
    ['learning', 'Grafana: dashboards that answer questions, not decorate'],
    ['learning', 'OpenTelemetry: instrumentation, spans, context propagation'],
    ['learning', 'SLI/SLO/error budgets: definitions and how they drive alerting'],
    ['learning', 'Alerting design: symptom vs cause, severity tiers, avoiding alert fatigue'],
    ['projects', 'Structured logging + request IDs in one service, end to end', 'Beginner'],
    ['projects', 'Prometheus + Grafana locally: instrument one app with the four golden signals', 'Beginner'],
    ['projects', 'Distributed tracing: OpenTelemetry across two services, inspect a full trace', 'Intermediate'],
    ['projects', 'Define SLOs + alert rules for one app, with a one-page runbook per alert', 'Intermediate'],
    ['confident', "Explain golden signals + what you'd alert on for a payments service, aloud"],
    ['confident', 'Narrate debugging a 3am latency spike using only dashboards + traces'],
    ['confident', 'Explain SLOs and error budgets to a non-SRE, cold'],
    ['confident', 'Cost + monitoring reasoning woven into every design answer'],
    ['continue', 'Monthly dashboard review of your own apps — prune dead panels, add missing signals'],
  ]),
  ...seed('ra', 'Resume & Apply', [
    ['revise', 'Audit current resume: tag every claim — can you defend it live?'],
    ['revise', 'Collect Amex impact metrics: scale, latency, cost, users'],
    ['revise', 'GitHub/portfolio cleanup: make Akshar Shiksha + DiagnoCare visible and polished'],
    ['learning', 'Master resume: Go+distributed systems headline, cloud + AI-assisted engineering section'],
    ['learning', 'One-line proof rule: every bullet maps to a project or story you can articulate'],
    ['learning', 'Two tailored variants: Java/GCP (Amex-type) and Go/AWS (product companies)'],
    ['learning', 'LinkedIn refresh; ATS-check both variants'],
    ['learning', 'Recruiter screen prep: 90-second pitch, salary deflection, availability script'],
    ['confident', 'Mock interviews: 1 per 2 weeks, weekly in interview season'],
    ['confident', 'Shortlist 20 targets, ranked; referral paths for top 10'],
    ['confident', 'Apply cadence: 5 quality applications/week, tracked in Notion'],
    ['confident', 'Per-interview company research via your Notion checklist'],
    ['confident', 'Salary negotiation page review; target + walk-away numbers set'],
    ['continue', 'Weekly pipeline review; post-interview retro after every round — every rejection produces data'],
    ['continue', 'Update resume after each completed project or new metric'],
  ]),
]
