import type { Problem } from './types'
import { addDays, todayISO } from './spacedRepetition'

const t = todayISO()

// Seed set with dates relative to "today" so the Due-for-revisit view and the
// rolling 7/30-day counts always have something to show in the demo.
export const seedProblems: Problem[] = [
  {
    id: 'p-two-sum',
    title: 'Two Sum',
    source: 'LeetCode',
    patterns: ['Arrays', 'Hash Map'],
    difficulty: 'Easy',
    status: 'solved',
    language: 'Python',
    timeTakenMinutes: 9,
    solutionNotes: 'One-pass hash map:\nfor i, n in enumerate(nums):\n    if target-n in seen: return [seen[target-n], i]\n    seen[n] = i',
    lastAttemptedDate: addDays(t, -2),
    nextRevisitDate: addDays(t, -1), // due
    revisitCount: 1,
  },
  {
    id: 'p-longest-substr',
    title: 'Longest Substring Without Repeating Characters',
    source: 'LeetCode',
    patterns: ['Sliding Window', 'Hash Map'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Go',
    timeTakenMinutes: 22,
    solutionNotes: 'Sliding window, move left pointer past last dup index.',
    lastAttemptedDate: addDays(t, -3),
    nextRevisitDate: t, // due today
    revisitCount: 1,
  },
  {
    id: 'p-lis',
    title: 'Longest Increasing Subsequence',
    source: 'LeetCode',
    patterns: ['DP', 'Binary Search'],
    difficulty: 'Medium',
    status: 'needs-revisit',
    language: 'Go',
    timeTakenMinutes: 35,
    solutionNotes: 'Patience sorting with binary search gives O(n log n).',
    lastAttemptedDate: addDays(t, -8),
    nextRevisitDate: addDays(t, -2), // overdue
    revisitCount: 1,
  },
  {
    id: 'p-course-schedule',
    title: 'Course Schedule',
    source: 'LeetCode',
    patterns: ['Graphs', 'Backtracking'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Java',
    timeTakenMinutes: 28,
    solutionNotes: 'Topological sort via Kahn’s algorithm (in-degree queue).',
    lastAttemptedDate: addDays(t, -5),
    nextRevisitDate: addDays(t, 2),
    revisitCount: 2,
  },
  {
    id: 'p-merge-intervals',
    title: 'Merge Intervals',
    source: 'LeetCode',
    patterns: ['Intervals', 'Arrays'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Python',
    timeTakenMinutes: 18,
    solutionNotes: 'Sort by start, merge when overlap.',
    lastAttemptedDate: addDays(t, -1),
    nextRevisitDate: addDays(t, 3),
    revisitCount: 1,
  },
  {
    id: 'p-valid-parens',
    title: 'Valid Parentheses',
    source: 'LeetCode',
    patterns: ['Stack'],
    difficulty: 'Easy',
    status: 'solved',
    language: 'Go',
    timeTakenMinutes: 7,
    solutionNotes: 'Stack of opening brackets, match on close.',
    lastAttemptedDate: addDays(t, -6),
    nextRevisitDate: addDays(t, 1),
    revisitCount: 1,
  },
  {
    id: 'p-num-islands',
    title: 'Number of Islands',
    source: 'LeetCode',
    patterns: ['Graphs', 'Backtracking'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Java',
    timeTakenMinutes: 21,
    solutionNotes: 'DFS flood fill, mark visited in-place.',
    lastAttemptedDate: addDays(t, -14),
    nextRevisitDate: addDays(t, 7),
    revisitCount: 2,
  },
  {
    id: 'p-coin-change',
    title: 'Coin Change',
    source: 'LeetCode',
    patterns: ['DP'],
    difficulty: 'Medium',
    status: 'attempted',
    language: 'Python',
    timeTakenMinutes: 40,
    solutionNotes: 'Unbounded knapsack; dp[amount] = min coins.',
    lastAttemptedDate: addDays(t, -4),
    revisitCount: 0,
  },
  {
    id: 'p-trapping-rain',
    title: 'Trapping Rain Water',
    source: 'LeetCode',
    patterns: ['Two Pointers', 'Arrays'],
    difficulty: 'Hard',
    status: 'needs-revisit',
    language: 'C#',
    timeTakenMinutes: 45,
    solutionNotes: 'Two pointers tracking left/right max.',
    lastAttemptedDate: addDays(t, -9),
    nextRevisitDate: addDays(t, -3), // overdue
    revisitCount: 1,
  },
  {
    id: 'p-word-ladder',
    title: 'Word Ladder',
    source: 'LeetCode',
    patterns: ['Graphs', 'Sliding Window'],
    difficulty: 'Hard',
    status: 'attempted',
    language: 'Java',
    solutionNotes: 'BFS over word graph; precompute wildcard buckets.',
    lastAttemptedDate: addDays(t, -12),
    revisitCount: 0,
  },
  {
    id: 'p-kth-largest',
    title: 'Kth Largest Element in an Array',
    source: 'HackerRank',
    patterns: ['Heap'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Python',
    timeTakenMinutes: 15,
    solutionNotes: 'Min-heap of size k, or quickselect.',
    lastAttemptedDate: addDays(t, -20),
    nextRevisitDate: addDays(t, 5),
    revisitCount: 2,
  },
  {
    id: 'p-reverse-ll',
    title: 'Reverse Linked List',
    source: 'LeetCode',
    patterns: ['Linked List'],
    difficulty: 'Easy',
    status: 'not-started',
    solutionNotes: '',
    revisitCount: 0,
  },
  {
    id: 'p-edit-distance',
    title: 'Edit Distance',
    source: 'Company',
    patterns: ['DP'],
    difficulty: 'Hard',
    status: 'not-started',
    solutionNotes: '',
    revisitCount: 0,
  },
  {
    id: 'p-search-rotated',
    title: 'Search in Rotated Sorted Array',
    source: 'LeetCode',
    patterns: ['Binary Search', 'Arrays'],
    difficulty: 'Medium',
    status: 'solved',
    language: 'Go',
    timeTakenMinutes: 19,
    solutionNotes: 'Modified binary search; decide which half is sorted.',
    lastAttemptedDate: addDays(t, -25),
    nextRevisitDate: addDays(t, -1), // due
    revisitCount: 3,
  },
]
