import type { ClaudeWeek } from './types'

export const seedClaudeWeeks: ClaudeWeek[] = [
  {
    id: 'cw-1',
    week: 1,
    title: 'Tool Use Fundamentals',
    material: "Anthropic's \"How tool use works\" + \"Tutorial: Build a tool-using agent\" (platform docs)",
    useCase: "Rebuild your saree photography agent's tool loop from scratch — define the tools explicitly (folder-watch, image-process, upload), handle the tool_use → tool_result cycle yourself instead of relying on a framework",
    deliverable: 'A working script that calls one real tool end-to-end',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-2',
    week: 2,
    title: 'Memory Tool + Tool Search Tool',
    material: 'Anthropic docs on the memory tool and tool search tool (newer additions)',
    useCase: 'Give the Anekriti pricing agent persistent memory of "items already reviewed" so it doesn\'t re-flag the same inventory every night',
    deliverable: 'Agent that remembers state across runs (JSON or SQLite-backed)',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-3',
    week: 3,
    title: 'MCP Server Development (production-grade)',
    material: 'MCP docs (server spec) + the mcp-builder skill reference already in your environment',
    useCase: "Build a real MCP server wrapping Anekriti's billing DB — expose \"get overdue payments,\" \"get low-margin items\" as callable tools",
    deliverable: 'MCP server running locally, callable from Claude Code',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-4',
    week: 4,
    title: 'Claude Agent SDK',
    material: 'Agent SDK quickstart + "Define your agent" docs',
    useCase: 'Port the Anekriti pricing agent onto Agent SDK (stateful session, persistent event history) — compare against your LangGraph version from earlier exploration',
    deliverable: 'Side-by-side notes on which fits Anekriti vs. Iterit better',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-5',
    week: 5,
    title: 'Claude Code Advanced (hooks, subagents, headless)',
    material: 'Claude Code docs — hooks, custom slash commands, headless/CI mode',
    useCase: 'Set up a Claude Code hook for Earlichamps that auto-runs tests/lint on every content-generation commit',
    deliverable: 'One working hook + one custom slash command used in a real Earlichamps task',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-6',
    week: 6,
    title: 'Skills (packaging expertise)',
    material: "Anthropic's Skills docs + skill-creator reference",
    useCase: "Write a Skill encoding Anekriti's pricing rules (margin bands, GST thresholds) so any agent instance applies them consistently instead of re-explaining them each time",
    deliverable: 'A SKILL.md file reusable across sessions',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-7',
    week: 7,
    title: 'Context Management for Long-Running Agents',
    material: 'Context management docs (context editing, compaction for long sessions)',
    useCase: "Apply this to Iterit's daily speaking-practice agent — it accumulates transcripts/RAG data over time and needs to stay efficient, not bloat the context every run",
    deliverable: 'Agent that runs daily without context growing unbounded',
    status: 'not-started',
    notes: '',
  },
  {
    id: 'cw-8',
    week: 8,
    title: 'Chaining Agents Together',
    material: 'Review everything built in weeks 1–7; no new material',
    useCase: 'Connect the Anekriti pricing agent → billing MCP server → a notification step (approval-gated), so the full loop runs with one human check-in instead of three separate manual steps',
    deliverable: 'One end-to-end chained workflow, live',
    status: 'not-started',
    notes: '',
  },
]
